// SPDX-License-Identifier: GPL-2.0-or-later
/**
 * @file
 * DecorationOptions implementation.
 */

#include "decoration-options.h"
#include "ui_decoration-options.h" // Generated by CMake AUTOUIC

#include <QButtonGroup>
#include <QPushButton>
#include <QRadioButton>
#include <QSignalBlocker>

#include "props/binder.h"
#include "props/property-def.h"
#include "qt/ui/color-picker.h"
#include "qt/ui/number-edit.h"

namespace Linea::UI {

DecorationOptions::DecorationOptions(QWidget* parent)
    : QWidget(parent)
    , _ui(std::make_unique<Ui::DecorationOptions>())
{
    _ui->setupUi(this);
    setupWidgets();
    setupConnections();
}

DecorationOptions::~DecorationOptions() = default;

void DecorationOptions::setupWidgets() {
    // Two independent radio groups: thickness mode and decoration color mode.
    // Without explicit groups, Qt auto-groups all radio buttons in the same
    // parent widget, so only one of all five could be checked at a time.
    auto* thicknessGroup = new QButtonGroup(this);
    thicknessGroup->setExclusive(true);
    thicknessGroup->addButton(_ui->thicknessAuto);
    thicknessGroup->addButton(_ui->thicknessFont);
    thicknessGroup->addButton(_ui->thicknessCustom);

    auto* colorGroup = new QButtonGroup(this);
    colorGroup->setExclusive(true);
    colorGroup->addButton(_ui->decorColorDefault);
    colorGroup->addButton(_ui->decorColorCustom);

    // Spin box configuration (range/decimals/step can't be set in the .ui).
    _ui->lineThickness->setRange(0.0, 100000.0);
    _ui->lineThickness->setDecimals(4);
    _ui->lineThickness->setSingleStep(0.1);

    // Color picker configuration.
    _ui->decorationColor->setTitle(tr("Text decoration"));
    _ui->decorationColor->setUndo(true);
    _ui->decorationColor->setUseTransparency(false);

    // Initial defaults.
    _ui->thicknessAuto->setChecked(true);
    _ui->decorColorDefault->setChecked(true);
    _ui->decorationColor->setEnabled(false);
}

void DecorationOptions::setupConnections() {
    // Line style — exclusive buttons emitting an int index.
    QPushButton* style_btns[] = {_ui->lineSolid, _ui->lineDouble, _ui->lineDotted, _ui->lineDashed, _ui->lineWavy};
    for (int i = 0; i < 5; ++i) {
        connect(style_btns[i], &QPushButton::toggled, this, [this, i](bool checked) {
            if (!checked) return;
            Q_EMIT lineStyleChanged(i);
        });
    }

    // Thickness — three modes; "Custom" enables the spin box.
    connect(_ui->thicknessAuto, &QRadioButton::toggled, this, [this](bool checked) {
        if (!checked) return;
        _ui->lineThickness->setEnabled(false);
        Q_EMIT thicknessChanged(DecorationThicknessState{0, true, false});
    });
    connect(_ui->thicknessFont, &QRadioButton::toggled, this, [this](bool checked) {
        if (!checked) return;
        _ui->lineThickness->setEnabled(false);
        Q_EMIT thicknessChanged(DecorationThicknessState{0, false, true});
    });
    connect(_ui->thicknessCustom, &QRadioButton::toggled, this, [this](bool checked) {
        if (!checked) return;
        _ui->lineThickness->setEnabled(true);
        Q_EMIT thicknessChanged(DecorationThicknessState{_ui->lineThickness->value(), false, false});
    });
    connect(_ui->lineThickness, &NumberEdit::valueChanged, this, [this](double value) {
        if (!_ui->thicknessCustom->isChecked()) return;
        Q_EMIT thicknessChanged(DecorationThicknessState{value, false, false});
    });

    // Decoration color — Default clears, Custom enables the picker.
    connect(_ui->decorColorDefault, &QRadioButton::toggled, this, [this](bool checked) {
        if (!checked) return;
        _ui->decorationColor->setEnabled(false);
        Q_EMIT decorationColorChanged(std::nullopt);
    });
    connect(_ui->decorColorCustom, &QRadioButton::toggled, this, [this](bool checked) {
        if (!checked) return;
        _ui->decorationColor->setEnabled(true);
    });
    _ui->decorationColor->connectChanged([this](const Inkscape::Colors::Color& color) {
        Q_EMIT decorationColorChanged(std::optional<Inkscape::Colors::Color>(color));
    });
}

// --- public state push -----------------------------------------------------

void DecorationOptions::setLineStyle(int style) {
    if (style < 0 || style > 4) return;
    QPushButton* style_btns[] = {_ui->lineSolid, _ui->lineDouble, _ui->lineDotted, _ui->lineDashed, _ui->lineWavy};
    const QSignalBlocker blockers[] = {
        QSignalBlocker(_ui->lineSolid),
        QSignalBlocker(_ui->lineDouble),
        QSignalBlocker(_ui->lineDotted),
        QSignalBlocker(_ui->lineDashed),
        QSignalBlocker(_ui->lineWavy),
    };
    for (int j = 0; j < 5; ++j) {
        style_btns[j]->setChecked(j == style);
    }
}

void DecorationOptions::setLineStyleMixed(bool mixed) {
    if (!mixed) return;
    const QSignalBlocker blockers[] = {
        QSignalBlocker(_ui->lineSolid),
        QSignalBlocker(_ui->lineDouble),
        QSignalBlocker(_ui->lineDotted),
        QSignalBlocker(_ui->lineDashed),
        QSignalBlocker(_ui->lineWavy),
    };
    for (auto* btn : {_ui->lineSolid, _ui->lineDouble, _ui->lineDotted, _ui->lineDashed, _ui->lineWavy}) {
        btn->setChecked(false);
    }
}

void DecorationOptions::setThickness(const DecorationThicknessState& state, bool mixed) {
    const QSignalBlocker bAuto(_ui->thicknessAuto);
    const QSignalBlocker bFont(_ui->thicknessFont);
    const QSignalBlocker bCustom(_ui->thicknessCustom);
    const QSignalBlocker bEdit(_ui->lineThickness);

    if (mixed) {
        _ui->thicknessAuto->setChecked(false);
        _ui->thicknessFont->setChecked(false);
        _ui->thicknessCustom->setChecked(false);
        _ui->lineThickness->setEnabled(false);
        return;
    }
    if (state.from_font) {
        _ui->thicknessFont->setChecked(true);
        _ui->lineThickness->setEnabled(false);
    } else if (!state.auto_val) {
        _ui->thicknessCustom->setChecked(true);
        _ui->lineThickness->setEnabled(true);
        _ui->lineThickness->setValue(state.value);
    } else {
        _ui->thicknessAuto->setChecked(true);
        _ui->lineThickness->setEnabled(false);
    }
}

void DecorationOptions::setDecorationColor(const std::optional<Inkscape::Colors::Color>& color, bool mixed) {
    const QSignalBlocker bDefault(_ui->decorColorDefault);
    const QSignalBlocker bCustom(_ui->decorColorCustom);

    _ui->decorationColor->setColor(color.value_or(Inkscape::Colors::Color(0)));
    if (mixed) {
        _ui->decorColorDefault->setChecked(false);
        _ui->decorColorCustom->setChecked(false);
    } else if (color) {
        _ui->decorColorCustom->setChecked(true);
    } else {
        _ui->decorColorDefault->setChecked(true);
    }
}

// --- declarative binding -----------------------------------------------------

void DecorationOptions::bind(Props::Binder& binder) {
    // Line style — push via bindField, write via editor->set().
    binder.bindField(Props::Field::decoration_style, [this](const Props::SelectionState& s) {
        if (s.typography.decoration_style.is_single() &&
            s.typography.decoration_style.value() >= 0 &&
            s.typography.decoration_style.value() < 5) {
            setLineStyle(s.typography.decoration_style.value());
        } else {
            setLineStyleMixed(true);
        }
    });
    binder.track(connect(this, &DecorationOptions::lineStyleChanged,
        [editor = binder.editor()](int style) {
            editor->set(Props::decoration_style, style);
        }));

    // Thickness — push via bindField, write via editor->set().
    binder.bindField(Props::Field::decoration_thickness, [this](const Props::SelectionState& s) {
        setThickness(s.typography.decoration_thickness.value(),
                     !s.typography.decoration_thickness.is_single());
    });
    binder.track(connect(this, &DecorationOptions::thicknessChanged,
        [editor = binder.editor()](const DecorationThicknessState& th) {
            editor->set(Props::decoration_thickness, th);
        }));

    // Color — push via bindField, write via editor->set().
    binder.bindField(Props::Field::decoration_color, [this](const Props::SelectionState& s) {
        if (s.typography.decoration_color.is_single()) {
            setDecorationColor(s.typography.decoration_color.value(), false);
        } else if (s.typography.decoration_color.is_unset()) {
            setDecorationColor(std::nullopt, false);
        } else {
            setDecorationColor(std::nullopt, true);
        }
    });
    binder.track(connect(this, &DecorationOptions::decorationColorChanged,
        [editor = binder.editor()](const std::optional<Inkscape::Colors::Color>& color) {
            editor->set(Props::decoration_color, color);
        }));
}

} // namespace Linea::UI
