// SPDX-License-Identifier: GPL-2.0-or-later
/**
 * @file
 * ExportWidget — dedicated export panel implementation.
 */

#include "export-widget.h"

#include <functional>

#include <QGridLayout>
#include <QIcon>
#include <QMenu>
#include <QPushButton>
#include <QVBoxLayout>

#include "extension/output.h"
#include "number-edit.h"
#include "props/binder.h"
#include "qt/ui/extension-selector.h"
#include "ui_export-widget.h" // Generated by CMake AUTOUIC
#include "popup-menu.h"

namespace Linea::UI {

namespace {

class SingleExport final : public QWidget {
public:
    explicit SingleExport(QWidget* parent = nullptr)
        : QWidget(parent)
    {
        auto layout = new QGridLayout(this);
        layout->setContentsMargins(0, 0, 0, 0);
        layout->setSpacing(4);
        layout->setColumnStretch(0, 1);
        layout->setColumnStretch(1, 1);
        layout->setColumnStretch(2, 0);
        layout->setColumnStretch(3, 0);

        auto dpiButton = new IconComboBox(this);
        dpiButton->setToolTip(tr("Choose image resolution"));
        dpiButton->addRow(QString(), tr("×1"), 96);
        dpiButton->addRow(QString(), tr("×2"), 192);
        dpiButton->addRow(QString(), tr("300 DPI"), 300);
        dpiButton->addRow(QString(), tr("600 DPI"), 600);
        dpiButton->addRow(QString(), tr("1200 DPI"), 1200);
        auto dpiEdit = new NumberEdit;
        dpiEdit->setLabel(tr("DPI"));
        dpiEdit->setRange(1, 100000);
        dpiEdit->setDecimals(0);
        dpiEdit->setValue(96);
        dpiButton->addPopupWidget(dpiEdit, 0);

        auto typeButton = new ExtensionSelector(this);
        typeButton->setToolTip(tr("Choose the export type"));

        auto optionsButton = new QPushButton(this);
        optionsButton->setIcon(QIcon(":/icons/gear"));
        optionsButton->setToolTip(tr("Export options"));

        auto removeButton = new QPushButton(this);
        removeButton->setIcon(QIcon(":/icons/minus"));
        removeButton->setToolTip(tr("Remove export task"));
        connect(removeButton, &QPushButton::clicked, this, [this] {
            if (_removeHandler) {
                _removeHandler();
            }
        });

        layout->addWidget(dpiButton, 0, 0);
        layout->addWidget(typeButton, 0, 1);
        layout->addWidget(optionsButton, 0, 2);
        layout->addWidget(removeButton, 0, 3);
        layout->setColumnStretch(0, 1);
        layout->setColumnStretch(1, 1);

        connect(optionsButton, &QPushButton::clicked, this, [this, typeButton, optionsButton] {
            showOptions(typeButton, optionsButton);
        });
    }

    void setRemoveHandler(std::function<void()> handler) {
        _removeHandler = std::move(handler);
    }

private:
    void showOptions(ExtensionSelector* selector, QPushButton* button) {
        auto extension = selector->selectedExtension();
        if (!extension) {
            return;
        }

        delete _optionsPopup;
        _optionsPopup = new PopupMenu(this);
        auto options = extension->autogui(nullptr, nullptr);
        if (!options) {
            delete _optionsPopup;
            _optionsPopup = nullptr;
            return;
        }

        _optionsPopup->setContent(options);
        _optionsPopup->showBelowWidget(button);
    }

    std::function<void()> _removeHandler;
    PopupMenu* _optionsPopup = nullptr;
};

} // namespace

ExportWidget::ExportWidget(QWidget* parent)
    : QWidget(parent)
    , _ui(std::make_unique<Ui::ExportWidget>())
{
    _ui->setupUi(this);
    updateExportButtonVisibility();

    connect(_ui->addExportButton, &QPushButton::clicked, this, &ExportWidget::addSingleExport);
}

ExportWidget::~ExportWidget() = default;

void ExportWidget::addSingleExport() {
    auto task = new SingleExport(_ui->exportTasksContainer);
    task->setRemoveHandler([this, task] { removeSingleExport(task); });
    _ui->exportTasksLayout->addWidget(task);
    updateExportButtonVisibility();
}

void ExportWidget::removeSingleExport(QWidget* task) {
    if (!task) {
        return;
    }

    _ui->exportTasksLayout->removeWidget(task);
    task->deleteLater();
    updateExportButtonVisibility();
}

void ExportWidget::updateExportButtonVisibility() {
    _ui->exportButton->setVisible(_ui->exportTasksLayout->count() > 0);
}

void ExportWidget::bind(Props::Binder& binder) {
    binder.visibleWhen(this, Props::Cond::hasSelection || Props::Cond::hasPageSelection);
}

} // namespace Linea::UI
