// SPDX-License-Identifier: GPL-2.0-or-later
/**
 * @file
 * FilterWidget implementation — Qt widget for managing a single filter.
 */

#include "filter-widget.h"

#include <QEvent>
#include <QLineEdit>
#include <QPushButton>
#include <QTreeWidget>
#include <QTreeWidgetItem>
#include <QVBoxLayout>
#include <cmath>
#include <functional>
#include <glibmm/i18n.h>

#include "desktop.h"
#include "document-undo.h"
#include "extension/db.h"
#include "extension/effect.h"
#include "filter-chemistry.h"
#include "filter-enums.h"
#include "filter-gallery.h"
#include "filter/filter-editor.h"
#include "object/sp-item.h"
#include "popup-menu.h"
#include "popup-tree-helper.h"
#include "props/binder.h"
#include "selection.h"
#include "spin-scale.h"
#include "ui/icon-names.h"
#include "ui_filter-widget.h" // Generated by CMake AUTOUIC

using namespace Inkscape;

namespace Linea::UI {

namespace {

// Matches the BLUR_MULTIPLIER used in filter-chemistry.cpp and the GTK panel.
constexpr double BLUR_MULTIPLIER = 4.0;

/// Apply a filter to the item and record undo. The apply callback is run
/// under an update block so the subsequent refresh doesn't re-enter the widget.
void applyFilterAndUndo(SPItem* spitem, OperationBlocker& update,
                        std::function<void()> apply) {
    auto scoped = update.block();
    apply();
    DocumentUndo::done(spitem->document, RC_("Undo", "Add filter"), INKSCAPE_ICON("dialog-filters"));
}

/// Look up an extension effect by ID. Returns nullptr if not found or not an Effect.
Inkscape::Extension::Effect* lookupEffect(const QString& id) {
    if (id.isEmpty()) return nullptr;

    auto ext = Inkscape::Extension::db.get(id.toUtf8().constData());
    return dynamic_cast<Inkscape::Extension::Effect*>(ext);
}

/// Populate a tree item as an extension filter leaf: display name (with a
/// trailing "..." when the effect takes parameters), the effect's ID in
/// UserRole, and -1 in UserRole+1 to mark it as an extension (not built-in).
void setExtensionLeaf(QTreeWidgetItem* item, Inkscape::Extension::Effect* effect) {
    if (!item || !effect) return;

    auto name = QString::fromUtf8(effect->get_name());
    if (effect->takes_input()) {
        name += QString::fromUtf8(_("..."));
    }
    item->setText(0, name);
    item->setData(0, Qt::UserRole, QString::fromUtf8(effect->get_id()));
    item->setData(0, Qt::UserRole + 1, -1); // marks extension (not built-in)
}

/// Create a new filter with the given primitive type and attach it to the item.
/// For Gaussian blur, use the blur-specific helper that computes radius from
/// a percentage of the bounding box; for all others, create a fresh filter
/// with a single primitive.
void add_filter_to_item(SPItem* item, Filters::FilterPrimitiveType type) {
    if (!item || !item->document) return;

    if (type == Filters::NR_FILTER_GAUSSIANBLUR) {
        // Default to 10% blur, matching the GTK "add blur" button.
        modify_filter_gaussian_blur_amount(item, 10.0);
        return;
    }

    auto filter = new_filter(item->document);
    filter_add_primitive(filter, type);
    sp_style_set_property_url(item, "filter", filter, false);
    item->updateRepr(SP_OBJECT_MODIFIED_FLAG | SP_OBJECT_STYLE_MODIFIED_FLAG);
}

/// Information about the filter currently attached to an object, for display.
struct FilterDisplayInfo {
    size_t count = 0;
    bool is_gaussian_blur = false;
    double blur_percent = 0.0;
    QString label;
};

FilterDisplayInfo get_filter_display_info(SPObject* object) {
    FilterDisplayInfo info;

    auto item = cast<SPItem>(object);
    if (!item) return info;

    info.count = get_filter_primitive_count(object);
    if (info.count == 0) return info;

    if (info.count == 1) {
        auto primitive = get_first_filter_component(object);
        if (primitive && primitive->getRepr()) {
            auto id = FPConverter.get_id_from_key(primitive->getRepr()->name());
            info.label = QString::fromUtf8(_(FPConverter.get_label(id).c_str()));
            if (id == Filters::NR_FILTER_GAUSSIANBLUR) {
                info.is_gaussian_blur = true;
                if (auto radius = object_query_blur_filter(item)) {
                    if (auto bbox = item->desktopGeometricBounds()) {
                        double perimeter = bbox->dimensions()[Geom::X] + bbox->dimensions()[Geom::Y];
                        if (perimeter > 0) {
                            info.blur_percent = std::sqrt(*radius * BLUR_MULTIPLIER / perimeter) * 100.0;
                        }
                    }
                }
            }
        }
    } else {
        // Without a reliable way to distinguish a single extension filter from
        // a merged/compound one, always use the generic label.
        info.label = QString::fromUtf8(_("Compound filter"));
    }

    return info;
}

} // anonymous namespace

FilterWidget::FilterWidget(QWidget* parent)
    : QWidget(parent)
    , _ui(std::make_unique<Ui::FilterWidget>()) {
    _ui->setupUi(this);

    // All content widgets exist upfront; refreshFilters only toggles
    // visibility and updates values. This avoids destroying the SpinScale
    // mid-drag (which would break continuous drag adjustment).
    _ui->blurLabel->setVisible(false);
    _ui->blurScale->setVisible(false);
    _ui->filterLabel->setVisible(false);
    _ui->filterButton->setVisible(false);
    _ui->removeButton->setVisible(false);

    connect(_ui->galleryButton, &QPushButton::clicked, this, &FilterWidget::onGalleryButtonClicked);
    connect(_ui->addButton, &QPushButton::clicked, this, &FilterWidget::onAddButtonClicked);
    connect(_ui->removeButton, &QPushButton::clicked, this, &FilterWidget::removeCurrentFilter);
    connect(_ui->filterButton, &QPushButton::clicked, this, &FilterWidget::onEditorButtonClicked);
    connect(_ui->blurScale, &SpinScale::valueChanged, this, [this](double value) {
        if (_update.pending() || !_object) return;
        auto scoped = _update.block();
        auto item = cast<SPItem>(_object);
        if (modify_filter_gaussian_blur_amount(item, value)) {
            DocumentUndo::maybeDone(_object->document, "change-blur-radius", RC_("Undo", "Change blur filter"),
                                    INKSCAPE_ICON("dialog-filters"));
        }
    });
}

FilterWidget::~FilterWidget() = default;

void FilterWidget::setObject(SPObject* object) {
    _objectDelete.disconnect();
    _object = object;
    if (_object) {
        _objectDelete = _object->connectDelete([this](SPObject* deleted) {
            if (deleted != _object) return;
            _object = nullptr;
            refreshFilters();
        });
    }
    refreshFilters();
}

void FilterWidget::setDesktop(SPDesktop* desktop) {
    _desktop = desktop;
}

void FilterWidget::bind(Linea::Props::Binder& binder) {
    _desktop = binder.editor()->desktop();
    if (!_desktop) return;

    // Track selection composition and identity. Binding to Field::counts
    // alone is not enough: switching from one single selection to another
    // doesn't change the count, so the callback wouldn't fire and _object
    // would point at the stale selection. Field::id changes whenever the
    // selected object's identity changes.
    auto updateObject = [this](const Linea::Props::SelectionState&) {
        if (!_desktop) return;
        auto sel = _desktop->getSelection();
        setObject(sel ? sel->single() : nullptr);
    };
    binder.bindField(Linea::Props::Field::counts, updateObject);
    binder.bindField(Linea::Props::Field::id, updateObject);
    binder.bindField(Linea::Props::Field::geometry, [this](const Linea::Props::SelectionState&) { refreshFilters(); });

    // Filter changes (e.g. applied from the pref dialog) are tracked via the
    // filter style field — fires when the filter URL or its primitives change.
    binder.bindField(Linea::Props::Field::filter, [this](const Linea::Props::SelectionState&) { refreshFilters(); });

    // Visible only for a single selection — filters apply per item.
    binder.visibleWhen(this, Linea::Props::Cond::singleSelection);
}

void FilterWidget::refreshFilters() {
    if (_update.pending()) return;
    auto scoped = _update.block();

    auto info = get_filter_display_info(_object);

    // Add button visible only when there is no filter.
    _ui->addButton->setVisible(info.count == 0);

    // Remove button visible whenever a filter is present.
    _ui->removeButton->setVisible(info.count > 0);

    if (info.count == 0) {
        _ui->blurLabel->setVisible(false);
        _ui->blurScale->setVisible(false);
        _ui->filterLabel->setVisible(false);
        _ui->filterButton->setVisible(false);
        return;
    }

    if (info.is_gaussian_blur) {
        _ui->filterLabel->setVisible(false);
        _ui->filterButton->setVisible(false);
        _ui->blurLabel->setVisible(true);
        _ui->blurScale->setVisible(true);
        _ui->blurScale->setValue(info.blur_percent);
    } else {
        // Non-blur filters show a button that opens the filter editor popup.
        _ui->blurLabel->setVisible(false);
        _ui->blurScale->setVisible(false);
        _ui->filterLabel->setVisible(false);
        _ui->filterButton->setVisible(true);
        _ui->filterButton->setText(info.label);
    }
}

void FilterWidget::onGalleryButtonClicked() {
    if (!_object) return;

    if (!_galleryPopup) {
        _galleryPopup = new PopupMenu(this);
        _filterGallery = new FilterGallery();
        _filterGallery->setFixedSize(640, 460);
        _galleryPopup->setContent(_filterGallery);

        auto applyGalleryEffect = [this](const QString& id) {
            if (_galleryPopup) {
                _galleryPopup->hide();
            }
            applyEffect(id);
        };
        connect(_filterGallery, &FilterGallery::itemActivated, this, applyGalleryEffect);
        connect(_filterGallery, &FilterGallery::actionRequested, this, applyGalleryEffect);
    }

    _galleryPopup->showLeftOfWidget(_ui->galleryButton);
}

void FilterWidget::onEditorButtonClicked() {
    if (!_desktop) return;

    if (!_editorPopup) {
        _editorPopup = new PopupMenu(this);
        _filterEditor = new FilterEditor();
        _filterEditor->setFixedSize(640, 720);
        _editorPopup->setContent(_filterEditor);
    }

    _filterEditor->setDesktop(_desktop);
    _editorPopup->showLeftOfWidget(_ui->filterButton);
}

void FilterWidget::onAddButtonClicked() {
    if (!_object) return;

    if (!_addPopup) {
        _addPopup = new PopupMenu(this);

        auto content = new QWidget();
        auto contentLayout = new QVBoxLayout(content);
        contentLayout->setContentsMargins(0, 0, 0, 0);
        contentLayout->setSpacing(4);

        _searchEdit = new QLineEdit(content);
        _searchEdit->setPlaceholderText(QString::fromUtf8(_("Search...")));
        contentLayout->addWidget(_searchEdit);

        _addList = new QTreeWidget(content);
        _addList->setFixedSize(240, 280);
        _addList->setHeaderHidden(true);
        _addList->setRootIsDecorated(true);
        _addList->setExpandsOnDoubleClick(false);
        _addList->setUniformRowHeights(true);
        _addList->setFocusPolicy(Qt::NoFocus); // keep focus on the search edit
        contentLayout->addWidget(_addList);

        connect(_searchEdit, &QLineEdit::textChanged, this, &FilterWidget::onSearchChanged);

        // Single click: expand/collapse categories, apply leaves.
        connect(_addList, &QTreeWidget::itemClicked, this, [this](QTreeWidgetItem* item) {
            if (!item) return;
            if (item->childCount() > 0) {
                item->setExpanded(!item->isExpanded());
            } else {
                applyTreeItem(item);
                _addPopup->hide();
            }
        });

        // Keyboard navigation: while the search box has focus, arrow keys
        // drive the tree selection and Enter applies the selected filter.
        _searchEdit->installEventFilter(this);

        _addPopup->setContent(content);

        populateAddPopup();
    }

    _addPopup->showLeftOfWidget(_ui->addButton);
    _searchEdit->clear();
    _searchEdit->setFocus();
}

void FilterWidget::populateAddPopup() {
    if (!_addList) return;
    _addList->clear();

    // Extension filters, organized into categories by get_menu_list() path.
    std::map<QString, QTreeWidgetItem*> categoryNodes;

    for (auto effect : Inkscape::Extension::db.get_effect_list()) {
        if (!effect->is_filter_effect()) continue;
        if (effect->hidden_from_menu()) continue;

        auto parent = _addList->invisibleRootItem();
        const auto& menuList = effect->get_menu_list();
        QString path;

        for (auto const& submenu : menuList) {
            auto name = QString::fromUtf8(submenu.c_str());
            path += "/" + name;

            auto it = categoryNodes.find(path);
            if (it == categoryNodes.end()) {
                auto node = new QTreeWidgetItem(parent);
                node->setText(0, name);
                categoryNodes[path] = node;
                parent = node;
            } else {
                parent = it->second;
            }
        }

        auto leaf = new QTreeWidgetItem(parent);
        setExtensionLeaf(leaf, effect);
    }

    _addList->sortByColumn(0, Qt::AscendingOrder);

    // Built-in Gaussian blur pinned at the top, above the sorted extension
    // categories. Inserted after the sort so it stays at index 0 and is not
    // reshuffled into its alphabetical position. Special-cased with a
    // percentage-based SpinScale UI.
    auto builtin = new QTreeWidgetItem();
    builtin->setText(0, QString::fromUtf8(_(FPConverter.get_label(Filters::NR_FILTER_GAUSSIANBLUR).c_str())));
    builtin->setData(0, Qt::UserRole, QString()); // empty ID marks built-in
    builtin->setData(0, Qt::UserRole + 1, static_cast<int>(Filters::NR_FILTER_GAUSSIANBLUR));
    _addList->insertTopLevelItem(0, builtin);
}

void FilterWidget::onSearchChanged() {
    if (!_addList) return;
    QString text = _searchEdit->text().toLower();

    for (int i = 0; i < _addList->topLevelItemCount(); ++i) {
        filterTreeItem(_addList->topLevelItem(i), text);
    }

    // Select the first visible leaf so Enter works right after filtering.
    auto first = Linea::UI::firstVisibleLeaf(_addList);
    if (first) {
        _addList->setCurrentItem(first);
    }
}

bool FilterWidget::filterTreeItem(QTreeWidgetItem* item, const QString& text) {
    bool isLeaf = item->childCount() == 0;

    if (isLeaf) {
        bool match = text.isEmpty() || item->text(0).toLower().contains(text);
        item->setHidden(!match);
        return match;
    }

    // Category: visible if any descendant matches.
    bool anyVisible = false;
    for (int i = 0; i < item->childCount(); ++i) {
        if (filterTreeItem(item->child(i), text)) {
            anyVisible = true;
        }
    }
    item->setHidden(!anyVisible);
    // Auto-expand categories while searching; collapse when search is cleared.
    item->setExpanded(anyVisible && !text.isEmpty());
    return anyVisible;
}

void FilterWidget::applyTreeItem(QTreeWidgetItem* item) {
    if (!item || item->childCount() > 0) return; // only leaves

    auto spitem = cast<SPItem>(_object);
    if (!spitem) return;

    auto id = item->data(0, Qt::UserRole).toString();

    if (id.isEmpty()) {
        // Built-in primitive (e.g. Gaussian blur).
        int typeInt = item->data(0, Qt::UserRole + 1).toInt();
        auto type = static_cast<Filters::FilterPrimitiveType>(typeInt);
        applyFilterAndUndo(spitem, _update, [&] { add_filter_to_item(spitem, type); });
        refreshFilters();
        return;
    }

    applyEffect(id);
}

void FilterWidget::applyEffect(const QString& id) {
    auto spitem = cast<SPItem>(_object);
    if (!spitem) return;

    auto effect = lookupEffect(id);
    if (!effect) return;

    if (effect->takes_input()) {
        // Effects with parameters: show pref dialog immediately.
        // The dialog applies the filter via effect() when the user
        // clicks Apply, and handles its own undo.
        if (_addPopup) {
            _addPopup->hide();
        }
        if (_galleryPopup) {
            _galleryPopup->hide();
        }
        effect->prefs(_desktop);
        refreshFilters();
        return;
    }

    // No parameters: apply immediately.
    applyFilterAndUndo(spitem, _update, [&] { effect->apply_filter(spitem); });
    refreshFilters();
}

void FilterWidget::removeCurrentFilter() {
    if (!_object) return;

    auto scoped = _update.block();
    remove_filter(_object, false);
    DocumentUndo::done(_object->document, RC_("Undo", "Remove filter"), INKSCAPE_ICON("dialog-filters"));
    refreshFilters();
}

void FilterWidget::onFilterButtonClicked() {
    // Post-creation filter editing is disabled until a way exists to map
    // existing filter primitives back to extension parameter values.
    // auto item = cast<SPItem>(_object);
    // if (!item || !item->style) return;
    // auto filter = item->style->getFilter();
    // if (!filter) return;
    // auto label = filter->getAttribute("inkscape:label");
    // if (!label || !*label) return;
    // auto effect = find_filter_effect(QString::fromUtf8(label));
    // if (!effect || !effect->takes_input()) return;
    // effect->prefs(_desktop);
}

bool FilterWidget::eventFilter(QObject* watched, QEvent* event) {
    if (watched == _searchEdit && event->type() == QEvent::KeyPress) {
        if (handlePopupTreeKey(static_cast<QKeyEvent*>(event), _addList, _addPopup,
                               [this](QTreeWidgetItem* item) {
                                   applyTreeItem(item);
                                   _addPopup->hide();
                               })) {
            return true;
        }
    }

    return QWidget::eventFilter(watched, event);
}

} // namespace Linea::UI
