// SPDX-License-Identifier: GPL-2.0-or-later
/** \file
 * Qt gradient selector widget implementation
 */

#include "gradient-selector.h"

#include <algorithm>

#include <QHeaderView>

#include "actions/actions-tools.h"
#include <QIcon>
#include <QKeyEvent>
#include <QTableWidgetItem>
#include <QToolButton>
#include <QSignalBlocker>

#include <cairomm/context.h>
#include <cairomm/surface.h>
#include <glibmm/i18n.h>

#include "display/cairo-utils.h"
#include "document.h"
#include "document-undo.h"
#include "gradient-chemistry.h"
#include "id-clash.h"
#include "inkscape.h"
#include "object/sp-defs.h"
#include "object/sp-gradient.h"
#include "object/sp-object-iterator.h" // Required for range-for iteration over SPRoot
#include "object/sp-root.h"
#include "object/sp-stop.h"
#include "ui/icon-names.h"

#include "ui_gradient-selector.h" // Generated by CMake AUTOUIC

using Inkscape::DocumentUndo;

namespace Linea::UI {

namespace {

// Convert Cairo surface to QPixmap
QPixmap surfaceToPixmap(const Cairo::RefPtr<Cairo::Surface>& surface, int width, int height) {
    if (!surface) return {};

    auto image = Cairo::ImageSurface::create(Cairo::Surface::Format::ARGB32, width, height);
    auto ctx = Cairo::Context::create(image);
    ctx->set_source(surface, 0, 0);
    ctx->paint();
    image->flush();

    // Cairo ARGB32 is premultiplied; copy to detach from the Cairo buffer.
    QImage qimage(image->get_data(), width, height, image->get_stride(), QImage::Format_ARGB32_Premultiplied);
    QImage copy = qimage.copy();
    return QPixmap::fromImage(copy);
}

// Draw gradient to Cairo surface
void drawGradient(SPGradient* gr, int width, int height, cairo_t* ct) {
    if (!gr) return;

    auto check = ink_cairo_pattern_create_checkerboard();
    cairo_set_source(ct, check->cobj());
    cairo_paint(ct);

    auto p = gr->create_preview_pattern(width);
    if (!p) return;
    cairo_set_source(ct, p);
    cairo_paint(ct);
    cairo_pattern_destroy(p);
}

// Convert gradient to QPixmap
QPixmap gradientToPixmap(SPGradient* gr, int width, int height) {
    cairo_surface_t* s = cairo_image_surface_create(CAIRO_FORMAT_ARGB32, width, height);
    cairo_t* ct = cairo_create(s);
    drawGradient(gr, width, height, ct);
    cairo_destroy(ct);
    cairo_surface_flush(s);

    auto surface = Cairo::RefPtr<Cairo::Surface>(new Cairo::Surface(s, true));
    QPixmap result = surfaceToPixmap(surface, width, height);
    return result;
}

// Return a "HHSSLL" version of the first stop color for sorting
unsigned long gradientToHhssll(SPGradient* gr) {
    if (!gr || !gr->getFirstStop()) return 0;
    auto hsl = gr->getFirstStop()->getColor();
    hsl.convert(Inkscape::Colors::Space::Type::HSL);
    return (static_cast<unsigned long>(hsl[0] * 100 * 10000) +
            static_cast<unsigned long>(hsl[1] * 100 * 100) +
            static_cast<unsigned long>(hsl[2] * 100));
}

// Prepare label for gradient
QString prepareLabel(SPObject* obj) {
    const gchar* id = obj->label() ? obj->label() : obj->getId();
    if (!id) {
        id = obj->getRepr()->name();
    }

    QString label = QString::fromUtf8(id);
    if (label.length() > 14 && (label.startsWith("linearGradient") || label.startsWith("radialGradient"))) {
        return label.mid(14);
    }
    return label;
}

// Ellipsize text if longer than maxlen
QString ellipsizeText(const QString& src, size_t maxlen) {
    if (src.length() > static_cast<int>(maxlen) && maxlen > 8) {
        size_t p1 = maxlen / 2;
        size_t p2 = src.length() - (maxlen - p1 - 1);
        return src.mid(0, static_cast<int>(p1)) + "\u2026" + src.mid(static_cast<int>(p2));
    }
    return src;
}

} // anonymous namespace

GradientSelector::GradientSelector(QWidget* parent)
    : QWidget(parent)
    , _ui(std::make_unique<Ui::GradientSelector>())
{
    _ui->setupUi(this);

    // Set up table
    _ui->gradientTable->setColumnWidth(0, _pixWidth + 8);  // Icon column
    _ui->gradientTable->setColumnWidth(1, 180);          // Name column
    _ui->gradientTable->setColumnWidth(2, 40);           // Count column
    _ui->gradientTable->horizontalHeader()->setStretchLastSection(false);
    _ui->gradientTable->horizontalHeader()->setSectionResizeMode(0, QHeaderView::Fixed);
    _ui->gradientTable->horizontalHeader()->setSectionResizeMode(1, QHeaderView::Stretch);
    _ui->gradientTable->horizontalHeader()->setSectionResizeMode(2, QHeaderView::Fixed);
    _ui->gradientTable->verticalHeader()->setDefaultSectionSize(_pixHeight + 4);

    // Set up button icons
    _ui->addButton->setIcon(QIcon::fromTheme("list-add"));
    _ui->delButton->setIcon(QIcon::fromTheme("list-remove"));
    _ui->del2Button->setIcon(QIcon::fromTheme("list-remove"));
    _ui->editButton->setIcon(QIcon::fromTheme("document-edit"));

    // Initially disable buttons
    _ui->addButton->setEnabled(false);
    _ui->delButton->setEnabled(false);
    _ui->del2Button->setEnabled(false);
    _ui->editButton->setEnabled(false);

    // Set up widget groups for mode switching
    _nonsolidWidgets = {_ui->addButton, _ui->del2Button, _ui->editButton};
    _swatchWidgets = {_ui->delButton};

    setupConnections();
}

GradientSelector::~GradientSelector() = default;

void GradientSelector::setupConnections() {
    connect(_ui->addButton, &QToolButton::clicked, this, &GradientSelector::onAddClicked);
    connect(_ui->delButton, &QToolButton::clicked, this, &GradientSelector::onDeleteClicked);
    connect(_ui->del2Button, &QToolButton::clicked, this, &GradientSelector::onDeleteUnusedClicked);
    connect(_ui->editButton, &QToolButton::clicked, this, &GradientSelector::onEditClicked);

    connect(_ui->gradientTable, &QTableWidget::itemSelectionChanged,
            this, &GradientSelector::onTableSelectionChanged);
    connect(_ui->gradientTable, &QTableWidget::cellChanged,
            this, &GradientSelector::onTableCellChanged);

    // Header click handling for sorting
    connect(_ui->gradientTable->horizontalHeader(), &QHeaderView::sectionClicked,
            [this](int column) {
                if (column == 0) {
                    onColorHeaderClicked();
                } else if (column == 1) {
                    onNameHeaderClicked();
                } else if (column == 2) {
                    onCountHeaderClicked();
                }
            });
}

void GradientSelector::setGradient(SPGradient* /*gradient*/) {
    // No-op - setVector handles the actual gradient setting
}

SPGradient* GradientSelector::getVector() const {
    return _gradient;
}

void GradientSelector::setVector(SPDocument* doc, SPGradient* vector) {
    if (vector && !vector->hasStops()) {
        return;
    }

    // Update document connections
    if (doc != _doc) {
        _doc = doc;
        _gradient = nullptr;
    }

    _gradient = vector;
    updateTable();
    selectGradientInTable(vector);

    // Update button states
    if (vector) {
        for (auto* widget : _nonsolidWidgets) {
            widget->setEnabled(true);
        }
        for (auto* widget : _swatchWidgets) {
            widget->setEnabled(true);
        }

        // Handle swatch mode
        if (_mode == MODE_SWATCH && vector->isSwatch()) {
            if (vector->isSolid()) {
                for (auto* widget : _nonsolidWidgets) {
                    widget->setVisible(false);
                }
            } else {
                for (auto* widget : _nonsolidWidgets) {
                    widget->setVisible(true);
                }
            }
        } else if (_mode != MODE_SWATCH) {
            for (auto* widget : _swatchWidgets) {
                widget->setVisible(false);
            }
            for (auto* widget : _nonsolidWidgets) {
                widget->setVisible(true);
            }
        }

        checkDeleteButton();
    } else {
        _ui->addButton->setEnabled(doc != nullptr);
        _ui->delButton->setEnabled(false);
        _ui->del2Button->setEnabled(false);
        _ui->editButton->setEnabled(false);
    }
}

void GradientSelector::setMode(SelectorMode mode) {
    if (mode == _mode) return;

    _mode = mode;

    if (mode == MODE_SWATCH) {
        for (auto* widget : _nonsolidWidgets) {
            widget->setVisible(false);
        }
        for (auto* widget : _swatchWidgets) {
            widget->setVisible(true);
        }
        _ui->gradientTable->horizontalHeaderItem(0)->setText(tr("Swatch"));
    } else {
        for (auto* widget : _nonsolidWidgets) {
            widget->setVisible(true);
        }
        for (auto* widget : _swatchWidgets) {
            widget->setVisible(false);
        }
        _ui->gradientTable->horizontalHeaderItem(0)->setText(tr("Gradient"));
    }

    updateTable();
}

void GradientSelector::setUnits(SPGradientUnits units) {
    _gradientUnits = units;
}

SPGradientUnits GradientSelector::getUnits() const {
    return _gradientUnits;
}

void GradientSelector::setSpread(SPGradientSpread spread) {
    _gradientSpread = spread;
}

SPGradientSpread GradientSelector::getSpread() const {
    return _gradientSpread;
}

void GradientSelector::showEditButton(bool show) {
    _ui->editButton->setVisible(show);
}

void GradientSelector::setNameColSize(int minWidth) {
    _ui->gradientTable->setColumnWidth(1, minWidth);
}

void GradientSelector::setGradientSize(int width, int height) {
    _pixWidth = width;
    _pixHeight = height;
    _ui->gradientTable->setColumnWidth(0, width + 8);
    _ui->gradientTable->verticalHeader()->setDefaultSectionSize(height + 4);
    updateTable();
}

void GradientSelector::updateTable() {
    QSignalBlocker blocker(_ui->gradientTable);

    _ui->gradientTable->clearContents();
    _ui->gradientTable->setRowCount(0);
    _gradients.clear();
    _usageCounts.clear();

    if (!_doc) {
        _ui->gradientTable->setRowCount(1);
        auto* item = new QTableWidgetItem(tr("No document selected"));
        _ui->gradientTable->setItem(0, 1, item);
        return;
    }

    if (!_gradient) {
        _ui->gradientTable->setRowCount(1);
        auto* item = new QTableWidgetItem(tr("No gradient selected"));
        _ui->gradientTable->setItem(0, 1, item);
        return;
    }

    // Collect gradients
    auto resources = _gradient->document->getResourceList("gradient");
    for (auto* obj : resources) {
        auto* gr = cast<SPGradient>(obj);
        if (gr && gr->hasStops() && gr->isSwatch() == (_mode == MODE_SWATCH)) {
            _gradients.push_back(gr);
        }
    }

    if (_gradients.empty()) {
        _ui->gradientTable->setRowCount(1);
        auto* item = new QTableWidgetItem(tr("No gradients in document"));
        _ui->gradientTable->setItem(0, 1, item);
        return;
    }

    // Calculate usage counts
    for (auto* obj : _doc->getRoot()) {
        auto* item = cast<SPItem>(obj);
        if (!item || !item->getId()) continue;

        SPGradient* gr = sp_item_get_gradient(item, true);  // fill
        if (gr) {
            _usageCounts[gr]++;
        }
        gr = sp_item_get_gradient(item, false);  // stroke
        if (gr) {
            _usageCounts[gr]++;
        }
    }

    // Sort gradients based on current sort column
    if (_sortColumn == 0) {
        // Sort by color (hhssll)
        std::sort(_gradients.begin(), _gradients.end(),
            [this](SPGradient* a, SPGradient* b) {
                bool less = gradientToHhssll(a) < gradientToHhssll(b);
                return _sortOrder == Qt::AscendingOrder ? less : !less;
            });
    } else if (_sortColumn == 1) {
        // Sort by name
        std::sort(_gradients.begin(), _gradients.end(),
            [this](SPGradient* a, SPGradient* b) {
                bool less = prepareLabel(a) < prepareLabel(b);
                return _sortOrder == Qt::AscendingOrder ? less : !less;
            });
    } else if (_sortColumn == 2) {
        // Sort by refcount
        std::sort(_gradients.begin(), _gradients.end(),
            [this](SPGradient* a, SPGradient* b) {
                bool less = _usageCounts[a] < _usageCounts[b];
                return _sortOrder == Qt::AscendingOrder ? less : !less;
            });
    }

    // Populate table
    _ui->gradientTable->setRowCount(static_cast<int>(_gradients.size()));

    for (size_t i = 0; i < _gradients.size(); ++i) {
        auto* gr = _gradients[i];
        int row = static_cast<int>(i);

        // Gradient icon
        QPixmap pixmap = gradientToPixmap(gr, _pixWidth, _pixHeight);
        auto* iconItem = new QTableWidgetItem();
        iconItem->setData(Qt::DecorationRole, pixmap);
        iconItem->setData(Qt::UserRole, QVariant::fromValue(static_cast<void*>(gr)));
        iconItem->setFlags(iconItem->flags() & ~Qt::ItemIsEditable);
        _ui->gradientTable->setItem(row, 0, iconItem);

        // Name
        QString label = ellipsizeText(prepareLabel(gr), 35);
        auto* nameItem = new QTableWidgetItem(label);
        nameItem->setData(Qt::UserRole, QVariant::fromValue(static_cast<void*>(gr)));
        nameItem->setFlags(nameItem->flags() | Qt::ItemIsEditable);
        _ui->gradientTable->setItem(row, 1, nameItem);

        // Refcount
        int count = _usageCounts[gr];
        auto* countItem = new QTableWidgetItem(QString::number(count));
        countItem->setData(Qt::UserRole, QVariant::fromValue(static_cast<void*>(gr)));
        countItem->setFlags(countItem->flags() & ~Qt::ItemIsEditable);
        _ui->gradientTable->setItem(row, 2, countItem);
    }
}

void GradientSelector::selectGradientInTable(SPGradient* vector) {
    if (!vector) return;

    QSignalBlocker blocker(_ui->gradientTable);
    for (int row = 0; row < _ui->gradientTable->rowCount(); ++row) {
        auto* item = _ui->gradientTable->item(row, 0);
        if (!item) continue;

        auto* gr = static_cast<SPGradient*>(item->data(Qt::UserRole).value<void*>());
        if (gr == vector) {
            _ui->gradientTable->selectRow(row);
            _ui->gradientTable->scrollToItem(item, QAbstractItemView::PositionAtCenter);
            break;
        }
    }
}

void GradientSelector::onTableSelectionChanged() {
    if (_blocked) return;

    auto selected = _ui->gradientTable->selectedItems();
    if (selected.isEmpty()) return;

    auto* item = selected.first();
    auto* gr = static_cast<SPGradient*>(item->data(Qt::UserRole).value<void*>());

    if (gr) {
        vectorSet(gr);
    }

    checkDeleteButton();
}

void GradientSelector::onTableCellChanged(int row, int column) {
    if (column != 1) return;  // Only handle name changes

    auto* item = _ui->gradientTable->item(row, column);
    if (!item) return;

    auto* gr = static_cast<SPGradient*>(item->data(Qt::UserRole).value<void*>());
    if (!gr) return;

    QString newText = item->text();
    QString currentLabel = prepareLabel(gr);

    if (!newText.isEmpty() && newText != currentLabel) {
        gr->setLabel(newText.toUtf8().constData());
        DocumentUndo::done(gr->document, RC_("Undo", "Rename gradient"), INKSCAPE_ICON("color-gradient"));
        item->setText(ellipsizeText(prepareLabel(gr), 35));
    }
}

void GradientSelector::onNameHeaderClicked() {
    if (_sortColumn == 1) {
        _sortOrder = (_sortOrder == Qt::AscendingOrder) ? Qt::DescendingOrder : Qt::AscendingOrder;
    } else {
        _sortColumn = 1;
        _sortOrder = Qt::AscendingOrder;
    }
    updateTable();
}

void GradientSelector::onColorHeaderClicked() {
    if (_sortColumn == 0) {
        _sortOrder = (_sortOrder == Qt::AscendingOrder) ? Qt::DescendingOrder : Qt::AscendingOrder;
    } else {
        _sortColumn = 0;
        _sortOrder = Qt::AscendingOrder;
    }
    updateTable();
}

void GradientSelector::onCountHeaderClicked() {
    if (_sortColumn == 2) {
        _sortOrder = (_sortOrder == Qt::AscendingOrder) ? Qt::DescendingOrder : Qt::AscendingOrder;
    } else {
        _sortColumn = 2;
        _sortOrder = Qt::AscendingOrder;
    }
    updateTable();
}

void GradientSelector::checkDeleteButton() {
    auto selected = _ui->gradientTable->selectedItems();
    if (selected.isEmpty()) {
        _ui->del2Button->setEnabled(false);
        return;
    }

    auto* item = selected.first();
    auto* gr = static_cast<SPGradient*>(item->data(Qt::UserRole).value<void*>());

    if (!gr || !_doc) {
        _ui->del2Button->setEnabled(false);
        return;
    }

    int count = _usageCounts[gr];
    bool canDelete = count < 2 && _gradients.size() > 1;
    _ui->del2Button->setEnabled(canDelete);
}

void GradientSelector::vectorSet(SPGradient* gr) {
    if (_blocked) return;

    _blocked = true;
    gr = sp_gradient_ensure_vector_normalized(gr);
    setVector(gr ? gr->document : nullptr, gr);
    Q_EMIT signalChanged(gr);
    _blocked = false;
}

void GradientSelector::moveSelection(int amount, bool down, bool toEnd) {
    auto selected = _ui->gradientTable->selectedItems();
    if (selected.isEmpty()) return;

    int currentRow = selected.first()->row();
    int newRow = currentRow;

    if (toEnd) {
        newRow = down ? _ui->gradientTable->rowCount() - 1 : 0;
    } else {
        newRow = down ? currentRow + amount : currentRow - amount;
    }

    newRow = std::clamp(newRow, 0, _ui->gradientTable->rowCount() - 1);

    if (newRow != currentRow) {
        _ui->gradientTable->selectRow(newRow);
        _ui->gradientTable->scrollToItem(_ui->gradientTable->item(newRow, 0), QAbstractItemView::PositionAtCenter);
    }
}

void GradientSelector::onKeyPressed(int key) {
    switch (key) {
        case Qt::Key_Up:
        case Qt::Key_K:
            moveSelection(1, false);
            break;
        case Qt::Key_Down:
        case Qt::Key_J:
            moveSelection(1, true);
            break;
        case Qt::Key_PageUp:
            moveSelection(5, false);
            break;
        case Qt::Key_PageDown:
            moveSelection(5, true);
            break;
        case Qt::Key_Home:
            moveSelection(0, false, true);
            break;
        case Qt::Key_End:
            moveSelection(0, true, true);
            break;
    }
}

void GradientSelector::onAddClicked() {
    if (!_doc) return;

    auto* gr = _gradient;
    auto* xmlDoc = _doc->getReprDoc();

    Inkscape::XML::Node* repr = nullptr;

    if (gr) {
        gr->getRepr()->removeAttribute("inkscape:collect");
        repr = gr->getRepr()->duplicate(xmlDoc);
        auto newId = generate_similar_unique_id(_doc, gr->getId());
        gr->setAttribute("id", newId.c_str());
        _doc->getDefs()->getRepr()->appendChild(repr);
    } else {
        repr = xmlDoc->createElement("svg:linearGradient");
        auto* stop = xmlDoc->createElement("svg:stop");
        stop->setAttribute("offset", "0");
        stop->setAttribute("style", "stop-color:#000;stop-opacity:1;");
        repr->appendChild(stop);
        Inkscape::GC::release(stop);

        stop = xmlDoc->createElement("svg:stop");
        stop->setAttribute("offset", "1");
        stop->setAttribute("style", "stop-color:#fff;stop-opacity:1;");
        repr->appendChild(stop);
        Inkscape::GC::release(stop);

        _doc->getDefs()->getRepr()->appendChild(repr);
        gr = cast<SPGradient>(_doc->getObjectByRepr(repr));
    }

    setVector(_doc, gr);
    selectGradientInTable(gr);
    vectorSet(gr);

    Inkscape::GC::release(repr);
}

void GradientSelector::onDeleteClicked() {
    auto selected = _ui->gradientTable->selectedItems();
    if (selected.isEmpty()) return;

    auto* item = selected.first();
    auto* gr = static_cast<SPGradient*>(item->data(Qt::UserRole).value<void*>());

    if (gr) {
        std::string id = gr->getId();
        sp_gradient_unset_swatch(SP_ACTIVE_DESKTOP, id);
    }
}

void GradientSelector::onDeleteUnusedClicked() {
    auto selected = _ui->gradientTable->selectedItems();
    if (selected.isEmpty()) return;

    auto* item = selected.first();
    auto* gr = static_cast<SPGradient*>(item->data(Qt::UserRole).value<void*>());

    if (!gr) return;

    auto* repr = gr->getRepr();
    if (!repr) return;

    repr->setAttribute("inkscape:collect", "always");

    // Select next or previous row
    int row = item->row();
    int newRow = row - 1;
    if (newRow < 0) {
        newRow = row + 1;
    }

    if (newRow >= 0 && newRow < _ui->gradientTable->rowCount()) {
        _ui->gradientTable->selectRow(newRow);
        _ui->gradientTable->scrollToItem(_ui->gradientTable->item(newRow, 0), QAbstractItemView::PositionAtCenter);
    }
}

void GradientSelector::onEditClicked() {
    // Invoke the gradient tool - button is typically hidden
    set_active_tool(SP_ACTIVE_DESKTOP, "Gradient");
}

void GradientSelector::keyPressEvent(QKeyEvent* event) {
    onKeyPressed(event->key());
    QWidget::keyPressEvent(event);
}

} // namespace Linea::UI
