// SPDX-License-Identifier: GPL-2.0-or-later
/**
 * @file
 * Guides panel — show/lock guides and guide colours (Qt version).
 */

#include "guides-panel.h"

#include <glibmm/i18n.h>
#include <numbers>
#include <QTimer>
#include <QScrollBar>

#include "ui_guides-panel.h" // Generated by CMake AUTOUIC
#include "document.h"
#include "document-undo.h"
#include "object/sp-guide.h"
#include "object/sp-namedview.h"
#include "guide-widget.h"

using Inkscape::DocumentUndo;

namespace Linea::UI {

namespace {

// void write_namedview_bool(SPNamedView* nv,
//                           Inkscape::Util::Internal::ContextString operation,
//                           SPAttr key, bool on)
// {
//     if (!nv || !nv->document) return;

//     nv->change_bool_setting(key, on);
//     nv->document->setModifiedSinceSave();
//     DocumentUndo::done(nv->document, operation, "");
// }

void write_namedview_color(SPNamedView* nv,
                           const char* undo_key,
                           Inkscape::Util::Internal::ContextString operation,
                           SPAttr color_key, SPAttr opacity_key,
                           Inkscape::Colors::Color const& color)
{
    if (!nv || !nv->document) return;

    nv->change_color(color_key, opacity_key, color);
    nv->document->setModifiedSinceSave();
    DocumentUndo::maybeDone(nv->document, undo_key, operation, "");
}

void updateGuideWidget(GuideWidget* widget, SPGuide* guide) {
    if (!widget || !guide) return;

    widget->setGuide(guide);
    widget->setGuideId(guide->getId() ? QString::fromUtf8(guide->getId()) : QString());
    widget->setLabel(guide->getLabel() ? QString::fromUtf8(guide->getLabel()) : QString());

    auto color = Inkscape::Colors::Color(guide->getColor());
    widget->setColor(color);

    auto point = guide->getPoint();
    widget->setPosition(point.x(), point.y());

    double angleRad = guide->angle();
    double angleDeg = angleRad * 180.0 / std::numbers::pi;
    widget->setAngle(angleDeg);

    widget->setLocked(guide->getLocked());
}

} // namespace

GuidesPanel::GuidesPanel(QWidget* parent)
    : QWidget(parent)
    , _ui(std::make_unique<Ui::GuidesPanel>())
{
    _ui->setupUi(this);

    _ui->guideColor->setTitle(tr("Guide color"));
    _ui->guideColor->setUndo(true);
    _ui->guideColor->setUseTransparency(true);

    _ui->guideHighlightColor->setTitle(tr("Highlight color"));
    _ui->guideHighlightColor->setUndo(true);
    _ui->guideHighlightColor->setUseTransparency(true);

    // Set initial colours before any update() call.
    _ui->guideColor->setColor(Inkscape::Colors::Color(0x0000ff99));
    _ui->guideHighlightColor->setColor(Inkscape::Colors::Color(0xff000099));

    connect(_ui->newGuideButton, &QPushButton::clicked, this, [this]() {
        if (!_namedview || !_namedview->document) return;
        // Create a new guide at the center of the document
        auto doc = _namedview->document;
        auto guide = SPGuide::createSPGuide(doc, Geom::Point(0, 0), Geom::Point(1, 0));
        if (guide) {
            DocumentUndo::done(doc, RC_("Undo", "Create new guide"), "");
            scrollToBottom();
        }
    });

    updatePlaceholder();
    setupConnections();
}

GuidesPanel::~GuidesPanel() = default;

void GuidesPanel::setNamedview(SPNamedView* namedview) {
    if (_namedview == namedview) return;

    _namedview = namedview;
    _document = namedview ? namedview->document : nullptr;
    watchDocument();
}

void GuidesPanel::watchDocument() {
    _resourcesChanged.disconnect();
    _commitConn.disconnect();

    if (!_document) return;

    _resourcesChanged = _document->connectResourcesChanged("guide", [this]() {
        // Defer to the next idle loop iteration so that the widget whose
        // action triggered the resource change finishes its handler cleanly.
        QTimer::singleShot(0, this, [this]() { update(_namedview); });
    });

    // This is a dubious approach, but to watch all guides while their panel is
    // visible it is convenient.
    // Guide position/angle changes via canvas drag call DocumentUndo::done,
    // which fires the commit signal but not resources-changed (the guide is
    // not added or removed, only modified). Listen to commit to catch those.
    _commitConn = _document->connectCommit([this]() {
        QTimer::singleShot(0, this, [this]() { update(_namedview); });
    });
}

void GuidesPanel::setupConnections() {
    // connect(_ui->showGuides, &SwitchWidget::toggled, this, [this](bool checked) {
    //     if (_update.pending() || !_namedview) return;
    //     write_namedview_bool(_namedview,
    //         RC_("Undo", "Toggle show guides"), SPAttr::SHOWGUIDES, checked);
    // });

    // connect(_ui->lockGuides, &QCheckBox::toggled, this, [this](bool checked) {
    //     if (_update.pending() || !_namedview) return;
    //     write_namedview_bool(_namedview,
    //         RC_("Undo", "Toggle lock guides"), SPAttr::INKSCAPE_LOCKGUIDES, checked);
    // });

    _ui->guideColor->connectChanged([this](Inkscape::Colors::Color const& color) {
        if (_update.pending() || !_namedview) return;
        write_namedview_color(_namedview, "guide-color",
            RC_("Undo", "Set guide color"),
            SPAttr::GUIDECOLOR, SPAttr::GUIDEOPACITY, color);
    });

    _ui->guideHighlightColor->connectChanged([this](Inkscape::Colors::Color const& color) {
        if (_update.pending() || !_namedview) return;
        write_namedview_color(_namedview, "guide-hi-color",
            RC_("Undo", "Set guide highlight color"),
            SPAttr::GUIDEHICOLOR, SPAttr::GUIDEHIOPACITY, color);
    });

    connect(_ui->createGuidesButton, &QPushButton::clicked, this, [this]() {
        if (!_namedview || !_namedview->document) return;
        sp_guide_create_guides_around_page(_namedview->document);
    });

    connect(_ui->deleteGuidesButton, &QPushButton::clicked, this, [this]() {
        if (!_namedview || !_namedview->document) return;
        sp_guide_delete_all_guides(_namedview->document);
    });
}

void GuidesPanel::update(SPNamedView* namedview) {
    _namedview = namedview;
    if (!namedview) {
        // Remove all guide widgets
        while (_ui->guideListLayout->count() > 0) {
            auto item = _ui->guideListLayout->takeAt(0);
            delete item->widget(); // Deleting the widget also deletes the layout item
        }
        updatePlaceholder();
        return;
    }

    auto scoped = _update.block();

    // _ui->showGuides->setChecked(namedview->getShowGuides());
    // _ui->lockGuides->setChecked(namedview->getLockGuides());
    _ui->guideColor->setColor(namedview->getGuideColor());
    _ui->guideHighlightColor->setColor(namedview->getGuideHiColor());

    const auto& guides = namedview->guides;

    // Count existing GuideWidget children
    int widgetCount = _ui->guideListLayout->count();
    int guideIndex = 0;

    // Sync existing widgets or add new ones
    while (guideIndex < static_cast<int>(guides.size())) {
        if (guideIndex < widgetCount) {
            // Update existing widget if it watches a different guide
            auto item = _ui->guideListLayout->itemAt(guideIndex);
            auto widget = qobject_cast<GuideWidget*>(item->widget());
            if (widget) {
                auto guide = guides[guideIndex];
                if (widget->guide() != guide) {
                    widget->setGuide(guide);
                }
                updateGuideWidget(widget, guide);
            }
        } else {
            addGuide(guides[guideIndex]);
        }
        guideIndex++;
    }

    // Remove excess widgets (iterate backwards)
    widgetCount = _ui->guideListLayout->count();
    while (widgetCount > static_cast<int>(guides.size())) {
        auto item = _ui->guideListLayout->takeAt(widgetCount - 1);
        delete item->widget(); // Deleting the widget also deletes the layout item
        widgetCount--;
    }

    updatePlaceholder();
}

void GuidesPanel::addGuide(SPGuide* guide) {
    if (!guide) return;

    auto widget = new GuideWidget(this);
    widget->setContentsMargins(0, 0, 0, 12);

    // Initialize the widget's properties before connecting signals so that
    // setting the initial values doesn't trigger document writes.
    updateGuideWidget(widget, guide);

    // Connect widget signals to update the guide
    connect(widget, &GuideWidget::labelChanged, this, [this, widget](const QString& label) {
        if (_update.pending()) return;
        if (auto guide = widget->guide()) {
            guide->set_label(label.toUtf8().constData(), true);
            DocumentUndo::done(guide->document, RC_("Undo", "Set guide label"), "");
        }
    });

    connect(widget, &GuideWidget::colorChanged, this, [this, widget](const Inkscape::Colors::Color& color) {
        if (_update.pending()) return;

        auto guide = widget->guide();
        auto rgba = color.toRGBA();
        guide->set_color(SP_RGBA32_R_U(rgba), SP_RGBA32_G_U(rgba), SP_RGBA32_B_U(rgba), SP_RGBA32_A_U(rgba), true);
        DocumentUndo::done(guide->document, RC_("Undo", "Set guide color"), "");
    });

    connect(widget, &GuideWidget::positionChanged, this, [this, widget](double x, double y) {
        if (_update.pending()) return;

        auto guide = widget->guide();
        guide->moveto(Geom::Point(x, y), true);
        DocumentUndo::done(guide->document, RC_("Undo", "Move guide"), "");
    });

    connect(widget, &GuideWidget::angleChanged, this, [this, widget](double angleDeg) {
        if (_update.pending()) return;

        auto guide = widget->guide();
        double angleRad = angleDeg * std::numbers::pi / 180.0;
        // Calculate new normal based on angle
        double nx = -std::sin(angleRad);
        double ny = std::cos(angleRad);
        guide->set_normal(Geom::Point(nx, ny), true);
        DocumentUndo::done(guide->document, RC_("Undo", "Set guide angle"), "");
    });

    connect(widget, &GuideWidget::lockedChanged, this, [this, widget](bool locked) {
        if (_update.pending()) return;

        auto guide = widget->guide();
        guide->set_locked(locked, true);
        DocumentUndo::done(guide->document, RC_("Undo", "Set guide lock state"), "");
    });

    connect(widget, &GuideWidget::deleteGuide, this, [this, widget]() {
        if (_update.pending()) return;

        auto guide = widget->guide();
        auto document = guide->document;
        if (guide->remove(true)) {
            DocumentUndo::done(document, RC_("Undo", "Delete guide"), "");
            delete widget;
        }
    });

    // Insert at the end
    int insertPos = _ui->guideListLayout->count();
    _ui->guideListLayout->insertWidget(insertPos, widget);

    updatePlaceholder();
}

void GuidesPanel::updatePlaceholder() {
    // Visible only when no guide widgets exist
    bool empty = _ui->guideListLayout->count() == 0;
    _ui->noGuidesLabel->setVisible(empty);
    _ui->guideListContainer->setVisible(!empty);
    // _ui->guideScroller->setVisible(!empty);
}

void GuidesPanel::scrollToBottom() {
    QTimer::singleShot(0, this, [this]() {
        // if (auto bar = _ui->guideScroller->verticalScrollBar()) {
        //     bar->setValue(bar->maximum());
        // }
    });
}

} // namespace Linea::UI
