// SPDX-License-Identifier: GPL-2.0-or-later
/** @file
 * ImageWidget implementation.
 *
 *//*
 * Authors:
 *   see git history
 *
 * Copyright (C) 2026 Authors
 * Released under GNU GPL v2+, read the file 'COPYING' for more information.
 */

#include "image-widget.h"

#include <QFileDialog>
#include <QImage>
#include <QLabel>
#include <QLineEdit>
#include <QMap>
#include <QPainter>
#include <QPixmap>
#include <QPushButton>
#include <algorithm>
#include <cstring>
#include <sstream>
#include <glibmm/i18n.h>

#include "display/cairo-utils.h"
#include "document-undo.h"
#include "document.h"
#include "number-edit.h"
#include "object/sp-image.h"
#include "props/binder.h"
#include "qt/ui/popup-menu.h"
#include "qt/ui/trace-panel.h"
#include "qt/util/drawing-utils.h"
#include "style-enums.h"
#include "trace/trace.h"
#include "ui/icon-names.h"
#include "ui/util.h"
#include "ui_image-widget.h" // Generated by CMake AUTOUIC
#include "util/format_size.h"
#include "xml/href-attribute-helper.h"

using Inkscape::DocumentUndo;

namespace Linea::UI {

namespace {

QPixmap draw_preview(const Inkscape::Pixbuf* image, double alpha, int width, int height, double device_scale,
                     const QColor& background) {
    if (!image) return {};

    QImage src = Inkscape::UI::cairo_surface_to_qimage(image->getSurfaceRaw());
    if (src.isNull()) return {};

    // minify to fit within width x height, preserving aspect ratio (smooth bilinear)
    src = src.scaled(width * device_scale, height * device_scale, Qt::KeepAspectRatio, Qt::FastTransformation);
    src.setDevicePixelRatio(device_scale);

    QImage out(src.size(), QImage::Format_ARGB32_Premultiplied);
    out.setDevicePixelRatio(device_scale);
    out.fill(Qt::transparent);

    QPainter p(&out);
    // checkerboard shows through where the image is not fully opaque
    if (alpha < 1.0) {
        p.setBrushOrigin(out.rect().topLeft());
        p.fillRect(out.rect(), QBrush(checkerPattern(background)));
    }
    p.setOpacity(alpha);
    p.drawImage(0, 0, src);
    p.end();

    return QPixmap::fromImage(out);
}

// Save 'pixbuf' image into a file. The format is inferred from the filename
// extension by Qt's image writer (Qt replacement for gdk_pixbuf_save).
bool save_png(const QString& fname, const Inkscape::Pixbuf* pixbuf) {
    if (fname.isEmpty() || !pixbuf) return false;

    Inkscape::Pixbuf image(*pixbuf);
    // Cairo stores premultiplied ARGB32, which maps onto QImage directly.
    image.ensurePixelFormat(Inkscape::Pixbuf::PF_CAIRO);

    // QImage wraps the buffer without copying; 'image' outlives the save() call.
    QImage qimage(image.pixels(), image.width(), image.height(), image.rowstride(),
                  QImage::Format_ARGB32_Premultiplied);
    return qimage.save(fname);
}

void populate_icon_combobox(IconComboBox* combo, const SPStyleEnum* table, const QMap<int, QString>& labels) {
    if (!combo || !table) return;
    for (int i = 0; table[i].key; ++i) {
        const auto& e = table[i];
        auto label = labels.value(e.value, QString::fromUtf8(e.key));
        combo->addRow(QString(), label, label, e.value);
    }
}

} // unnamed namespace

ImageWidget::ImageWidget(QWidget* parent)
    : QWidget(parent)
    , _ui(std::make_unique<Ui::ImageWidget>()) {
    _ui->setupUi(this);

    _ui->dpiEdit->setRange(1.0, 2400.0);
    _ui->dpiEdit->setDecimals(4);
    _ui->dpiEdit->setValue(96.0);

    const QMap<int, QString> renderingLabels = {
        {SP_CSS_IMAGE_RENDERING_AUTO, tr("Automatic")},
        {SP_CSS_IMAGE_RENDERING_OPTIMIZESPEED, tr("Optimize speed")},
        {SP_CSS_IMAGE_RENDERING_OPTIMIZEQUALITY, tr("Optimize quality")},
        {SP_CSS_IMAGE_RENDERING_CRISPEDGES, tr("Crisp edges")},
        {SP_CSS_IMAGE_RENDERING_PIXELATED, tr("Pixelated")},
    };
    populate_icon_combobox(_ui->renderingCombo, enum_image_rendering, renderingLabels);

    connect(_ui->changeButton, &QPushButton::clicked, this, &ImageWidget::onChangeImage);
    connect(_ui->exportButton, &QPushButton::clicked, this, &ImageWidget::onExportImage);
    connect(_ui->embedButton, &QPushButton::clicked, this, &ImageWidget::onEmbed);
    connect(_ui->traceBtn, &QPushButton::clicked, this, &ImageWidget::onTrace);
}

ImageWidget::~ImageWidget() = default;

void ImageWidget::bind(Linea::Props::Binder& binder) {
    _desktop = binder.editor()->desktop();

    _ui->renderingCombo->setHeaderType(IconComboBox::LabelOnly);

    binder.bind(Linea::Props::image_url, _ui->hrefEdit);
    binder.bind(Linea::Props::image_dpi, _ui->dpiEdit);
    binder.bind(Linea::Props::image_preserve_aspect, _ui->aspectGroup);
    binder.bind(Linea::Props::image_rendering, _ui->renderingCombo);

    auto updateInfo = [this](const Linea::Props::SelectionState& s) {
        const auto& e = s.element;
        if (e.image_dimensions.is_mixed() || e.image_embedded.is_mixed() || e.image_linked.is_mixed() ||
            e.image_color_space.is_mixed() || e.image_missing.is_mixed()) {
            _ui->infoLabel->setText("-");
            return;
        }

        if (e.image_missing.is_single() && e.image_missing.value()) {
            _ui->infoLabel->setText(_("Missing image"));
            return;
        }

        std::ostringstream ost;
        if (e.image_dimensions.is_single()) {
            const auto& [w, h] = e.image_dimensions.value();
            auto times = "\u00d7"; // multiplication sign
            ost << w << times << h << " px\n";
        }

        if (e.image_embedded.is_single() && e.image_embedded.value()) {
            ost << _("Embedded");
            if (e.image_data_size.is_single()) {
                ost << " (" << Inkscape::Util::format_file_size(e.image_data_size.value()) << ")";
            }
            ost << '\n';
        } else if (e.image_linked.is_single() && e.image_linked.value()) {
            ost << _("Linked") << '\n';
        }

        if (e.image_color_space.is_single() && !e.image_color_space.value().empty()) {
            ost << _("Color profile:") << ' ' << e.image_color_space.value() << '\n';
        }

        _ui->infoLabel->setText(QString::fromUtf8(ost.str().c_str()));
    };

    binder.bindField(Linea::Props::Field::image_dimensions, updateInfo);
    binder.bindField(Linea::Props::Field::image_embedded, updateInfo);
    binder.bindField(Linea::Props::Field::image_linked, updateInfo);
    binder.bindField(Linea::Props::Field::image_color_space, updateInfo);
    binder.bindField(Linea::Props::Field::image_missing, updateInfo);
    binder.bindField(Linea::Props::Field::image_data_size, updateInfo);

    auto updateUrlEnable = [this](const Linea::Props::SelectionState& s) {
        const auto& e = s.element;
        _ui->hrefEdit->setEnabled(e.image_embedded.is_single() && !e.image_embedded.value());
    };
    binder.bindField(Linea::Props::Field::image_embedded, updateUrlEnable);

    binder.bindField(Linea::Props::Field::image_pixbuf, [this](const Linea::Props::SelectionState&) {
        if (!_desktop) return;
        auto sel = _desktop->getSelection();
        setImage(sel ? dynamic_cast<SPImage*>(sel->single()) : nullptr);
    });
    binder.bindField(Linea::Props::Field::opacity, [this](const Linea::Props::SelectionState& s) {
        if (!_image || !_image->style) return;
        update(_image->pixbuf, _image->style->opacity.as_double());
    });

    // only show image properties when all selected items are images
    binder.visibleWhen(this, Linea::Props::Cond::allOf<&Linea::Props::Counts::images>);
}

void ImageWidget::setImage(SPImage* image) {
    if (image == _image) return;

    _image = image;
    auto opacity = image && image->style ? image->style->opacity.as_double() : 1.0;
    update(image ? image->pixbuf : nullptr, opacity);
}

void ImageWidget::update(std::shared_ptr<const Inkscape::Pixbuf> pixbuf, double opacity) {
    if (pixbuf != _pixbuf || _imageOpacity != opacity) {
        _pixbuf = pixbuf;
        _imageOpacity = opacity;
        resetPreview();
    }
    rebuildPreview();
}

void ImageWidget::resetPreview() {
    _hasPreview = false;
    _ui->previewLabel->setPixmap(QPixmap());
}

void ImageWidget::rebuildPreview() {
    if (_hasPreview) return;

    int width = _ui->previewLabel->width();
    int height = _ui->previewLabel->height();

    double device_scale = devicePixelRatioF();
    auto base = palette().base().color();
    _ui->previewLabel->setPixmap(draw_preview(_pixbuf.get(), _imageOpacity, width, height, device_scale, base));
    _hasPreview = true;
}

// TODO - move this to helper functions out of the UI
void ImageWidget::onChangeImage() {
    if (_update.pending() || !_image) return;

    QString file =
        QFileDialog::getOpenFileName(this, tr("Change Image"), QString(),
                                     tr("Images (*.png *.jpg *.jpeg *.gif *.bmp *.tif *.tiff *.svg);;All Files (*)"));
    if (file.isEmpty()) return;

    char* uri = g_filename_to_uri(file.toUtf8().constData(), nullptr, nullptr);
    if (!uri) return;
    Inkscape::setHrefAttribute(*_image->getRepr(), uri);
    g_free(uri);

    // SPImage modifies size when href changes; trigger it now before undo concludes
    _image->document->_updateDocument(0);
    DocumentUndo::done(_image->document, RC_("Undo", "Change image"), INKSCAPE_ICON("shape-image"));

    resetPreview();
    // todo
    //  update(_image);
}

void ImageWidget::onExportImage() {
    if (_update.pending() || !_image || !_image->pixbuf) return;

    QString file =
        QFileDialog::getSaveFileName(this, tr("Extract Image"), QStringLiteral("image.png"), tr("PNG Image (*.png)"));
    if (file.isEmpty()) return;

    save_png(file, _image->pixbuf.get());
}

void ImageWidget::onEmbed() {
    if (_update.pending() || !_image || !_image->pixbuf) return;

    // embed image in the current document
    Inkscape::Pixbuf copy(*_image->pixbuf);
    sp_embed_image(_image->getRepr(), &copy);
    DocumentUndo::done(_image->document, RC_("Undo", "Embed image"), INKSCAPE_ICON("selection-make-bitmap-copy"));
}

void ImageWidget::onTrace() {
    if (!_image || !_image->pixbuf) return;

    // Build a BitmapView from the pixbuf's cairo surface (ARGB32 premultiplied).
    const auto* pb = _image->pixbuf.get();
    Inkscape::Trace::BitmapView bmp{pb->width(), pb->height(), pb->rowstride(), pb->pixels()};

    // Lazily create the trace panel (reused across popups).
    if (!_tracePanel) {
        _tracePanel = new TracePanel(this);
        connect(_tracePanel, &TracePanel::traceRequested, this, [this] {
            _traceFuture.cancel();
            auto engine = _tracePanel->takeEngine();
            _traceFuture = Inkscape::Trace::trace(
                std::move(engine), _tracePanel->sioxEnabled(),
                [this](double frac) { _tracePanel->setTraceProgress(frac); },
                [this] { _tracePanel->setTraceComplete(); });
        });
        connect(_tracePanel, &TracePanel::previewRequested, this, [this] {
            _previewFuture.cancel();
            auto engine = _tracePanel->takeEngine();
            _previewFuture = Inkscape::Trace::preview(std::move(engine), _tracePanel->sioxEnabled(),
                                                      [this](QImage img) { _tracePanel->setPreview(std::move(img)); });
        });
        connect(_tracePanel, &TracePanel::traceAborted, this, [this] { _traceFuture.cancel(); });
    }
    _tracePanel->setImage(bmp);

    auto popup = new Linea::UI::PopupMenu(this);
    popup->setContent(_tracePanel);
    popup->showLeftOfWidget(_ui->traceBtn);
}

} // namespace Linea::UI
