// SPDX-License-Identifier: GPL-2.0-or-later
/**
 * @file
 * LpeWidget implementation — Qt widget for managing Live Path Effects.
 */

#include "lpe-widget.h"

#include <QEvent>
#include <QHBoxLayout>
#include <QLabel>
#include <QLineEdit>
#include <QListWidget>
#include <QListWidgetItem>
#include <QMouseEvent>
#include <QPushButton>
#include <QVBoxLayout>
#include <algorithm>

#include "desktop.h"
#include "document-undo.h"
#include "inkscape.h"
#include "live_effects/effect-enum.h"
#include "live_effects/effect.h"
#include "live_effects/lpe-common.h"
#include "live_effects/lpeobject-reference.h"
#include "live_effects/lpeobject.h"
#include "object/sp-lpe-item.h"
#include "object/sp-path.h"
#include "object/sp-shape.h"
#include "object/sp-use.h"
#include "popup-menu.h"
#include "preferences.h"
#include "props/binder.h"
#include "selection.h"
#include "ui/icon-names.h"
#include "ui_lpe-widget.h" // Generated by CMake AUTOUIC
#include "util-string/ustring-format.h"

using namespace Inkscape;
using namespace Inkscape::LivePathEffect;

namespace Linea::UI {

namespace {

/// Apply an LPE of the given type to the item.
void apply_lpeffect(SPItem* item, LivePathEffect::EffectType type) {
    if (!item) return;
    auto key = LivePathEffect::LPETypeConverter.get_key(type);
    LivePathEffect::Effect::createAndApply(key.c_str(), item->document, item);
    DocumentUndo::done(item->document, RC_("Undo", "Create and apply path effect"),
                       INKSCAPE_ICON("dialog-path-effects"));
}

/// Remove the LPE at the given index from the object.
void remove_lpeffect(SPObject* object, int index) {
    auto lpe_item = cast<SPLPEItem>(object);
    if (!lpe_item || !lpe_item->path_effect_list) return;

    int i = 0;
    for (auto&& lpe : *lpe_item->path_effect_list) {
        if (index == i) {
            if (auto effect = lpe->lpeobject ? lpe->lpeobject->get_lpe() : nullptr) {
                lpe_item->removePathEffect(effect, false);
                DocumentUndo::done(object->document, RC_("Undo", "Removed live path effect"),
                                   INKSCAPE_ICON("dialog-path-effects"));
            }
            break;
        }
        i++;
    }
}

/// Get the list of applied LPEs as (effect, index) pairs.
std::vector<std::pair<LivePathEffect::Effect*, int>> get_applied_lpes(SPObject* object) {
    std::vector<std::pair<LivePathEffect::Effect*, int>> result;
    auto lpe_item = cast<SPLPEItem>(object);
    if (!lpe_item || !lpe_item->path_effect_list) return result;

    int index = 0;
    for (auto&& lpe : *lpe_item->path_effect_list) {
        if (auto effect = lpe->lpeobject ? lpe->lpeobject->get_lpe() : nullptr) {
            result.emplace_back(effect, index);
        }
        index++;
    }
    return result;
}

/// Get the PathEffectSharedPtr at the given index, or nullptr.
PathEffectSharedPtr get_lperef_at_index(SPObject* object, int index) {
    auto lpe_item = cast<SPLPEItem>(object);
    if (!lpe_item || !lpe_item->path_effect_list) return nullptr;

    int i = 0;
    for (auto&& lpe : *lpe_item->path_effect_list) {
        if (i == index) {
            return lpe;
        }
        i++;
    }
    return nullptr;
}

/// Get the Effect at the given index, or nullptr.
LivePathEffect::Effect* get_effect_at_index(SPObject* object, int index) {
    auto lperef = get_lperef_at_index(object, index);
    return lperef && lperef->lpeobject ? lperef->lpeobject->get_lpe() : nullptr;
}

} // anonymous namespace

LpeWidget::LpeWidget(QWidget* parent)
    : QWidget(parent)
    , _ui(std::make_unique<Ui::LpeWidget>()) {
    _ui->setupUi(this);
    _ui->listLayout->addStretch();
    _ui->headerLabel->setCursor(Qt::PointingHandCursor);
    _ui->headerLabel->installEventFilter(this);
    connect(_ui->addButton, &QPushButton::clicked, this, &LpeWidget::onAddButtonClicked);
}

LpeWidget::~LpeWidget() = default;

void LpeWidget::setObject(SPObject* object) {
    _objectRelease.disconnect();
    _object = object;
    if (_object) {
        _objectRelease = _object->connectRelease([this](SPObject* released) {
            if (released != _object) return;
            _object = nullptr;
            refreshAppliedLpes();
        });
    }
    refreshAppliedLpes();
}

void LpeWidget::setDesktop(SPDesktop* desktop) {
    _desktop = desktop;
}

void LpeWidget::bind(Linea::Props::Binder& binder) {
    _desktop = binder.editor()->desktop();
    if (!_desktop) return;

    // Track the selected object so the widget always reflects the current
    // single-item selection (LPEs are per-item). Binding to Field::counts
    // alone misses identity changes (single A → single B); Field::id fires
    // whenever the selected object's identity changes.
    auto updateObject = [this](const Linea::Props::SelectionState&) {
        if (!_desktop) return;
        auto sel = _desktop->getSelection();
        setObject(sel ? sel->single() : nullptr);
    };
    binder.bindField(Linea::Props::Field::counts, updateObject);
    binder.bindField(Linea::Props::Field::id, updateObject);

    // LPE list changes (e.g. applied/removed/undo/redo) are tracked via the
    // lpe_count field — fires when the path-effect list size changes.
    binder.bindField(Linea::Props::Field::lpe_count, [this](const Linea::Props::SelectionState&) {
        refreshAppliedLpes();
    });

    // Visible only for a single selection of LPE-capable items (shapes, paths,
    // groups — i.e. SPLPEItem subclasses, not images or text).
    binder.visibleWhen(this, [](const Linea::Props::SelectionState& s) {
        if (!Linea::Props::Cond::singleSelection(s)) return false;
        const auto& c = s.element.count;
        int lpe_capable = c.paths + c.rectangles + c.ellipses + c.stars + c.polygon_paths + c.lines + c.groups;
        return lpe_capable == c.items;
    });
}

void LpeWidget::refreshAppliedLpes() {
    if (_update.pending()) return;
    auto scoped = _update.block();

    // Clear existing rows (keep the stretch item at the end)
    while (_ui->listLayout->count() > 1) {
        auto item = _ui->listLayout->takeAt(0);
        if (item->widget()) item->widget()->deleteLater();
        delete item;
    }

    if (!_object) {
        return;
    }

    auto applied = get_applied_lpes(_object);
    if (applied.empty()) {
        return;
    }

    for (auto& [effect, index] : applied) {
        auto row = new QWidget();
        auto rowLayout = new QHBoxLayout(row);
        rowLayout->setContentsMargins(2, 2, 0, 2);
        rowLayout->setSpacing(4);

        auto icon_name = LivePathEffect::LPETypeConverter.get_icon(effect->effectType());

        auto lpeBtn = new QPushButton(row);
        lpeBtn->setIcon(QIcon(":/icons/" + QString::fromStdString(icon_name)));
        lpeBtn->setText(QString::fromStdString(effect->getName().raw()));
        lpeBtn->setToolTip(QString::fromUtf8(_("Click to edit parameters")));
        lpeBtn->setStyleSheet("text-align: left; padding-left: 6px;");
        connect(lpeBtn, &QPushButton::clicked, this, [this, index, lpeBtn]() {
            showLpeParams(index, lpeBtn);
        });
        rowLayout->addWidget(lpeBtn, 1);

        // Flatten button: bake the effect into the path geometry
        auto flattenBtn = new QPushButton(row);
        flattenBtn->setToolTip(QString::fromUtf8(_("Flatten path effect")));
        flattenBtn->setIcon(QIcon(":/icons/flatten"));

        connect(flattenBtn, &QPushButton::clicked, this, [this, index]() {
            flattenLpe(index);
        });

        rowLayout->addWidget(flattenBtn);

        // Visibility toggle button: show/hide the effect
        auto visBtn = new QPushButton(row);
        bool visible = effect->isVisible();
        visBtn->setToolTip(QString::fromUtf8(visible ? _("Hide effect") : _("Show effect")));
        visBtn->setIcon(QIcon(visible ? ":/icons/object-visible" : ":/icons/object-hidden"));

        connect(visBtn, &QPushButton::clicked, this, [this, index]() {
            toggleLpeVisibility(index);
        });

        rowLayout->addWidget(visBtn);

        // Remove button
        auto removeBtn = new QPushButton(row);
        removeBtn->setToolTip(QString::fromUtf8(_("Remove effect")));
        removeBtn->setIcon(QIcon(":/icons/minus"));

        connect(removeBtn, &QPushButton::clicked, this, [this, index]() {
            removeLpe(index);
        });

        rowLayout->addWidget(removeBtn);

        _ui->listLayout->insertWidget(_ui->listLayout->count() - 1, row);
    }
}

void LpeWidget::onAddButtonClicked() {
    if (!_object) return;

    if (!_addPopup) {
        _addPopup = new PopupMenu(this);

        auto content = new QWidget();
        auto contentLayout = new QVBoxLayout(content);
        contentLayout->setContentsMargins(0, 0, 0, 0);
        contentLayout->setSpacing(4);

        _searchEdit = new QLineEdit(content);
        _searchEdit->setPlaceholderText(QString::fromUtf8(_("Search...")));
        contentLayout->addWidget(_searchEdit);

        _addList = new QListWidget(content);
        _addList->setFixedSize(220, 250);
        // _addList->setFixedHeight(260);
        _addList->setFocusPolicy(Qt::NoFocus); // keep focus on the search edit
        contentLayout->addWidget(_addList);

        connect(_searchEdit, &QLineEdit::textChanged, this, &LpeWidget::onSearchChanged);
        connect(_addList, &QListWidget::itemClicked, [this](QListWidgetItem* item) {
            if (!item) return;
            int typeInt = item->data(Qt::UserRole).toInt();
            applyLpe(typeInt);
            _addPopup->hide();
        });

        // Keyboard navigation: while the search box has focus, arrow keys
        // drive the list selection and Enter applies the selected LPE.
        _searchEdit->installEventFilter(this);

        _addPopup->setContent(content);
    }

    populateAddPopup();
    _addPopup->showLeftOfWidget(_ui->addButton);
    _searchEdit->clear();
    _searchEdit->setFocus();
}

void LpeWidget::populateAddPopup() {
    if (!_addList) return;
    _addList->clear();

    auto lpe_item = cast<SPLPEItem>(_object);
    if (!lpe_item) return;

    bool use = is<SPUse>(_object);
    bool experimental = Preferences::get()->getBool("/dialogs/livepatheffect/showexperimental", false);

    auto list = Linea::get_list_of_applicable_lpes(lpe_item, use, experimental);

    // Sort by label
    std::sort(list.begin(), list.end(), [](const auto& a, const auto& b) { return a.label < b.label; });

    for (const auto& lpe : list) {
        if (!lpe.sensitive) continue;

        auto item = new QListWidgetItem();
        item->setText(QString::fromStdString(lpe.label));
        item->setToolTip(QString::fromStdString(lpe.tooltip));
        item->setData(Qt::UserRole, static_cast<int>(lpe.type));

        item->setIcon(QIcon(":/icons/" + QString::fromStdString(lpe.icon_name)));

        _addList->addItem(item);
    }
}

void LpeWidget::onSearchChanged() {
    if (!_addList) return;
    QString text = _searchEdit->text().toLower();

    for (int i = 0; i < _addList->count(); ++i) {
        auto item = _addList->item(i);
        bool match = text.isEmpty() || item->text().toLower().contains(text);
        item->setHidden(!match);
    }

    // Select the first visible item so Enter works right after filtering.
    for (int i = 0; i < _addList->count(); ++i) {
        if (!_addList->item(i)->isHidden()) {
            _addList->setCurrentRow(i);
            break;
        }
    }
}

void LpeWidget::applyLpe(int lpeTypeInt) {
    auto item = cast<SPItem>(_object);
    if (!item) return;

    auto type = static_cast<LivePathEffect::EffectType>(lpeTypeInt);
    apply_lpeffect(item, type);
    refreshAppliedLpes();
}

void LpeWidget::removeLpe(int index) {
    if (!_object) return;

    remove_lpeffect(_object, index);
    refreshAppliedLpes();
}

void LpeWidget::flattenLpe(int index) {
    auto lpe_item = cast<SPLPEItem>(_object);
    auto lperef = get_lperef_at_index(_object, index);
    if (!lpe_item || !lperef) return;

    lpe_item->setCurrentPathEffect(lperef);
    lpe_item = lpe_item->flattenCurrentPathEffect();
    if (!lpe_item) return;
    setObject(lpe_item);

    auto selection = _desktop ? _desktop->getSelection() : nullptr;
    if (selection && selection->isEmpty()) {
        selection->add(lpe_item);
    }
    DocumentUndo::done(_object->document, RC_("Undo", "Flatten path effect(s)"),
                       INKSCAPE_ICON("dialog-path-effects"));
    refreshAppliedLpes();
}

void LpeWidget::toggleLpeVisibility(int index) {
    auto lpe_item = cast<SPLPEItem>(_object);
    auto effect = get_effect_at_index(_object, index);
    if (!lpe_item || !effect) return;

    auto repr = effect->getRepr();
    if (!repr) return;

    bool visible = !effect->isVisible();
    repr->setAttribute("is_visible", visible ? "true" : "false");
    effect->doOnVisibilityToggled(lpe_item);
    DocumentUndo::done(_object->document,
                       visible ? RC_("Undo", "Activate path effect")
                               : RC_("Undo", "Deactivate path effect"),
                       INKSCAPE_ICON("dialog-path-effects"));
    refreshAppliedLpes();
}

void LpeWidget::showLpeParams(int index, QWidget* anchorWidget) {
    if (!_object) return;

    auto effect = get_effect_at_index(_object, index);
    if (!effect) return;

    // Close any existing param popup
    _paramPopup.reset();

    auto popup = std::make_unique<PopupMenu>(this);

    auto content = new QWidget();
    auto contentLayout = new QVBoxLayout(content);
    contentLayout->setContentsMargins(0, 0, 0, 0);
    contentLayout->setSpacing(4);

    // Header with effect name
    auto header = new QLabel(QString::fromStdString(effect->getName().raw()), content);
    QFont headerFont = header->font();
    headerFont.setBold(true);
    header->setFont(headerFont);
    contentLayout->addWidget(header);

    // The parameter widget from the LPE
    if (auto paramWidget = effect->buildUI()) {
        contentLayout->addWidget(paramWidget);
    } else {
        auto noParams = new QLabel(QString::fromUtf8(_("<small>Without parameters</small>")), content);
        noParams->setMargin(5);
        contentLayout->addWidget(noParams);
    }

    popup->setContent(content);
    _paramPopup = std::move(popup);
    _paramPopup->showBelowWidget(anchorWidget);
}

bool LpeWidget::eventFilter(QObject* watched, QEvent* event) {
    if (watched == _ui->headerLabel && event->type() == QEvent::MouseButtonRelease) {
        auto mouseEvent = static_cast<QMouseEvent*>(event);
        if (mouseEvent->button() == Qt::LeftButton) {
            onAddButtonClicked();
            return true;
        }
    }

    // Keyboard navigation for the add-LPE popup: while the search box has
    // focus, arrow up/down move the list selection and Enter applies it.
    if (watched == _searchEdit && event->type() == QEvent::KeyPress) {
        auto keyEvent = static_cast<QKeyEvent*>(event);
        int key = keyEvent->key();
        if (key == Qt::Key_Up || key == Qt::Key_Down) {
            int count = _addList->count();
            if (count == 0) return true;
            int dir = (key == Qt::Key_Down) ? 1 : -1;
            int row = _addList->currentRow();
            if (row < 0) row = (dir > 0) ? -1 : count; // start from edge
            // Find the next visible item in the given direction.
            for (int i = row + dir; i >= 0 && i < count; i += dir) {
                if (!_addList->item(i)->isHidden()) {
                    _addList->setCurrentRow(i);
                    _addList->scrollToItem(_addList->item(i));
                    break;
                }
            }
            return true;
        }
        if (key == Qt::Key_Return || key == Qt::Key_Enter) {
            auto item = _addList->currentItem();
            if (item && !item->isHidden()) {
                int typeInt = item->data(Qt::UserRole).toInt();
                applyLpe(typeInt);
                _addPopup->hide();
            }
            return true;
        }
        if (key == Qt::Key_Escape) {
            _addPopup->hide();
            return true;
        }
    }

    return QWidget::eventFilter(watched, event);
}

} // namespace Linea::UI
