// SPDX-License-Identifier: GPL-2.0-or-later
/**
 * @file
 * PagesPanel — document pages list with a toolbar.
 */

#include "pages-panel.h"

#include <QPainter>
#include <QTimer>
#include <algorithm>
#include <cmath>
#include <glibmm/i18n.h>

#include "actions/action-registry.h"
#include "colors/color.h"
#include "document.h"
#include "object/sp-item.h"
#include "object/sp-page.h"
#include "object/sp-root.h"
#include "page-manager.h"
#include "ui/util.h"
#include "ui_pages-panel.h" // Generated by CMake AUTOUIC
#include "util/preview.h"
#include "virtual-tree-list.h"

namespace Linea::UI {

class PagesPanel::PagePreviewDrawing {
public:
    PagePreviewDrawing() = default;
    ~PagePreviewDrawing() { destruct(); }

    // not copyable because of the vision key / drawing state
    PagePreviewDrawing(const PagePreviewDrawing&) = delete;
    PagePreviewDrawing& operator=(const PagePreviewDrawing&) = delete;

    void construct(SPDocument* document) {
        destruct();
        _document = document;
        if (!_document) return;

        if (auto* root = _document->getRoot()) {
            _visionkey = SPItem::display_key_new(1);
            _drawing = std::make_shared<Inkscape::Drawing>();
            if (auto* di = root->invoke_show(*_drawing, _visionkey, SP_ITEM_SHOW_DISPLAY)) {
                _drawing->setRoot(di);
            }
        }
    }

    void destruct() {
        if (!_drawing || !_visionkey) return;
        if (_document) {
            if (auto root = _document->getRoot()) {
                root->invoke_hide(_visionkey);
            }
        }
        _drawing.reset();
        _visionkey = 0;
        _document = nullptr;
    }

    std::shared_ptr<Inkscape::Drawing> drawing() const { return _drawing; }
    unsigned visionkey() const { return _visionkey; }
    bool valid() const { return _drawing != nullptr; }

private:
    SPDocument* _document = nullptr;
    std::shared_ptr<Inkscape::Drawing> _drawing;
    unsigned _visionkey = 0;
};

PagesPanel::PagesPanel(QWidget* parent)
    : QWidget(parent)
    , _ui(std::make_unique<Ui::PagesPanel>()) {
    _ui->setupUi(this);

    _preview = std::make_unique<PagePreviewDrawing>();

    _list = _ui->list;
    _list->setExpanderEnabled(false);
    _list->setHoverEnabled(true);
    _list->setHasFrame(false);
    _list->setHasActiveBackground(false);
    _list->setRowGap(0);
    // _list->setRowSeparatorsEnabled(false);

    _list->setGetRowHeightFunc([this](const VirtualTreeList::ItemIndex& index) {
        if (!_document || _maxPageRect.width() <= 0) return _previewSize;

        auto page_rect = getPageRect(index.itemIndex);
        if (page_rect.width() <= 1 || page_rect.height() <= 1) return _previewSize;

        constexpr double page_margin = 10.0;
        double scale = (_previewSize - 2 * page_margin) / _maxPageRect.width();
        return std::max(1, static_cast<int>(std::round(page_rect.height() * scale + 2 * page_margin + 2 * _margin)));
    });

    _list->setDrawItemFunc(
        [this](QPainter* painter, const VirtualTreeList::ItemIndex& index, const QRect& rect, bool selected) {
            if (!_document) return;

            auto& pm = _document->getPageManager();
            auto page = pm.getPage(index.itemIndex);

            painter->save();

            if (selected) {
                // painter->fillRect(rect, palette().color(QPalette::Highlight));
                painter->setPen(palette().color(QPalette::HighlightedText));
            } else {
                painter->setPen(palette().color(QPalette::WindowText));
            }

            // render preview directly for each paint
            qreal dpr = painter->device() ? painter->device()->devicePixelRatioF() : 1.0;
            auto img = renderPagePreview(index.itemIndex, dpr);

            int preview_h = _previewSize;
            if (!img.isNull()) {
                preview_h = static_cast<int>(std::round(img.height() / dpr));
            }
            int previewTop = rect.top() + (rect.height() - preview_h) / 2;
            QRect previewRect(rect.left() + 4, previewTop, _previewSize, preview_h);
            if (!img.isNull()) {
                painter->drawImage(previewRect, img);
            }

            QString label;
            if (page) {
                label = QString::fromStdString(page->getLabel());
                if (label.isEmpty()) {
                    label = QString::fromUtf8(_("Page %1")).arg(page->getPagePosition());
                }
            } else {
                label = QString::fromUtf8(_("Page 1"));
            }

            auto textRect = rect.adjusted(4 + _previewSize, 0, -4, 0);
            painter->drawText(textRect, Qt::AlignLeft | Qt::AlignVCenter, label);

            painter->restore();
        });

    connect(_list, &VirtualTreeList::selectionChanged, this, [this](const VirtualTreeList::ItemIndex& index) {
        onSelectionChanged(index.isValid() ? index.itemIndex : -1);
    });

    auto connect_action = [](QPushButton* button, const char* id) {
        auto& registry = ActionRegistry::get();
        auto action = registry.action(id);
        QObject::connect(button, &QPushButton::clicked, button, [action] { action->trigger(); });
    };
    connect_action(_ui->newButton, "page-new");
    connect_action(_ui->deleteButton, "page-delete");
}

PagesPanel::~PagesPanel() = default;

void PagesPanel::setDesktop(SPDesktop* desktop) {
    _desktop = desktop;
}

void PagesPanel::setDocument(SPDocument* document) {
    if (_document == document) return;

    _document = document;
    _preview_cache.clear();
    _preview->construct(_document);
    watchDocument();
}

void PagesPanel::watchDocument() {
    _pagesChanged.disconnect();
    _pageSelected.disconnect();
    _pageModified.disconnect();

    if (!_document) return;

    auto& pm = _document->getPageManager();

    _pagesChanged = pm.connectPagesChanged([this](SPPage*) {
        QTimer::singleShot(0, this, [this]() {
            if (_document) update(_document);
        });
    });

    _pageSelected = pm.connectPageSelected([this](SPPage*) {
        QTimer::singleShot(0, this, [this]() {
            if (_document) updateSelection();
        });
    });

    _pageModified = pm.connectPageModified([this](SPPage*) {
        QTimer::singleShot(0, this, [this]() {
            if (!_document) return;
            rebuildMaxPageRect();
            _list->invalidate();
            updateSelection();
        });
    });
}

void PagesPanel::rebuildMaxPageRect() {
    if (!_document) {
        _maxPageRect = Geom::Rect();
        return;
    }

    auto& pm = _document->getPageManager();
    auto count = pm.getPageCount();
    bool document_page = count == 0;
    if (document_page) {
        count = 1;
    }

    double max_w = 0.0;
    double max_h = 0.0;
    if (document_page) {
        if (auto bounds = _document->preferredBounds()) {
            max_w = bounds->width();
            max_h = bounds->height();
        }
    } else {
        for (int i = 0; i < count; ++i) {
            if (auto* p = pm.getPage(i)) {
                auto r = p->getDocumentRect();
                max_w = std::max(max_w, r.width());
                max_h = std::max(max_h, r.height());
            }
        }
    }
    _maxPageRect = Geom::Rect(0, 0, max_w, max_h);
}

void PagesPanel::update(SPDocument* document) {
    _document = document;
    _preview_cache.clear();

    if (!_document) {
        _list->setItemCount(0);
        _ui->deleteButton->setEnabled(false);
        return;
    }

    rebuildMaxPageRect();

    auto& pm = _document->getPageManager();
    auto count = pm.getPageCount();
    _ui->deleteButton->setEnabled(count >= 2);
    if (count == 0) count = 1;

    _list->setItemCount(count);
    updateSelection();
}

void PagesPanel::updateSelection() {
    if (!_document) return;

    auto& pm = _document->getPageManager();
    auto count = pm.getPageCount();
    bool document_page = count == 0;
    if (document_page) count = 1;

    auto selectedIndex = pm.getSelectedPageIndex();
    if (document_page && selectedIndex < 0) {
        selectedIndex = 0;
    }
    if (selectedIndex >= 0 && selectedIndex < count) {
        _list->setSelectedItem(VirtualTreeList::ItemIndex(selectedIndex));
    } else {
        _list->setSelectedItem(VirtualTreeList::ItemIndex());
    }
}

Geom::Rect PagesPanel::getPageRect(int index) const {
    if (!_document || index < 0) return {};
    auto page = _document->getPageManager().getPage(index);
    if (page) {
        return page->getDocumentRect();
    }
    if (auto bounds = _document->preferredBounds()) {
        return *bounds;
    }
    return {};
}

QImage PagesPanel::renderPagePreview(int index, qreal dpr) {
    auto drawing = _preview->drawing();
    if (!_document || !drawing || !drawing->root() || dpr <= 0) return {};

    auto page_rect = getPageRect(index);
    if (page_rect.width() <= 0 || page_rect.height() <= 0) return {};

    auto& pm = _document->getPageManager();

    auto page_color = pm.getBackgroundColor().toRGBA();
    auto border_color = pm.getBorderColor().toRGBA();
    auto shadow_color = pm.getShadowColor().toRGBA();
    auto show_border = pm.getShowBorder();
    auto show_shadow = pm.getShowShadow();

    auto scaled_size = static_cast<unsigned>(std::round(_previewSize * dpr));
    unsigned scaled_height = scaled_size;
    if (_maxPageRect.width() > 0) {
        double margin = 10.0 * dpr;
        double scale = (scaled_size - 2 * margin) / _maxPageRect.width();
        scaled_height = static_cast<unsigned>(std::round(page_rect.height() * scale + 2 * margin));
    }
    scaled_height = std::max(scaled_height, 2U);

    PreviewKey key(index, dpr, scaled_size, scaled_height, static_cast<std::uint32_t>(page_color),
                   static_cast<std::uint32_t>(border_color), static_cast<std::uint32_t>(shadow_color), show_border,
                   show_shadow);
    if (auto cached = _preview_cache.get(key)) {
        return *cached;
    }

    auto surface = Inkscape::UI::Preview::render_page_preview(_document, drawing, page_rect, page_color, border_color,
                                                              shadow_color, show_border, show_shadow, scaled_size,
                                                              scaled_height, dpr);

    if (!surface) return {};

    surface->flush();
    QImage img = Inkscape::UI::cairo_surface_to_qimage(surface->cobj());
    if (img.isNull()) return {};

    _preview_cache.insert(key, img);
    return img;
}

void PagesPanel::onSelectionChanged(int index) {
    if (!_document || index < 0) return;

    auto page = _document->getPageManager().getPage(index);
    if (_document->getPageManager().selectPage(page) && _desktop) {
        _document->getPageManager().zoomToSelectedPage(_desktop);
    }
}

} // namespace Linea::UI
