// SPDX-License-Identifier: GPL-2.0-or-later

// Simple paint selector widget
// https://gitlab.com/inkscape/ux/-/issues/246

#include "paint-selector.h"

#include "adaptive-stack.h"
#include "ui_paint-selector.h" // Generated by CMake AUTOUIC

#include <array>
#include <cassert>
#include <map>

#include <QAction>
#include <QButtonGroup>
#include <QHBoxLayout>
#include <QLabel>
#include <QMenu>
#include <QStackedWidget>
#include <QToolButton>
#include <QVBoxLayout>

#include <glib.h>
#include <glib/gi18n.h>

#include "colors/color-set.h"
#include "colors/manager.h"
#include "colors/spaces/base.h"
#include "document.h"
#include "helper/stock-items.h"
#include "object/sp-gradient.h"
#include "object/sp-hatch.h"
#include "object/sp-linear-gradient.h"
#include "object/sp-mesh-gradient.h"
#include "object/sp-pattern.h"
#include "object/sp-radial-gradient.h"
#include "object/sp-stop.h"
#include "preferences.h"
#include "style-internal.h"
#include "actions/actions-tools.h"
#include "ui/operation-blocker.h"
#include "ui/widget/gradient-selector-interface.h"
#include "util/style-utils.h"

#include "qt/ui/color-picker-panel.h"
#include "qt/ui/gradient-editor.h"
#include "qt/ui/mesh-editor.h"
#include "qt/ui/paint-inherited.h"
#include "qt/ui/pattern-editor.h"

using namespace Inkscape::Colors;
using namespace Inkscape::Colors::Space;
using namespace Inkscape::UI;
using namespace Inkscape::UI::Widget;

namespace Linea::UI {

// ---------------------------------------------------------------------------
// paint_modes table
// ---------------------------------------------------------------------------
namespace {

const struct { PaintMode mode; const char* icon; const char* tip; } paint_modes[] = {
    {PaintMode::Solid,    "paint-solid",           _("Flat color")},
    // {PaintMode::CssSwatch,"paint-swatch",      _("Swatch color (CSS variable)")},
    {PaintMode::Gradient, "paint-gradient-linear", _("Linear gradient fill")},
#ifdef WITH_MESH
    {PaintMode::Mesh,     "paint-gradient-mesh",   _("Mesh fill")},
#endif
    // Note: there's no hatch mode; hatches are "patterns"
    {PaintMode::Pattern,  "paint-pattern",         _("Pattern and hatch fill")},
    // {PaintMode::LegacySwatch,   "paint-gradient-linear", _("Legacy swatch color")},
    {PaintMode::Derived,  "paint-unknown",         _("Inherited")},
    {PaintMode::None,     "paint-none",            _("No paint")},
};

} // namespace

// ---------------------------------------------------------------------------
// Free functions
// ---------------------------------------------------------------------------
QString get_paint_mode_icon(PaintMode mode) {
    for (auto& p : paint_modes) {
        if (p.mode == mode) return p.icon;
    }
    return {};
}

QString get_paint_mode_name(PaintMode mode) {
    for (auto& p : paint_modes) {
        if (p.mode == mode) return p.tip;
    }
    return {};
}

// ---------------------------------------------------------------------------
// FlatColorEditor — wraps ColorPickerPanel with prefs-persisted plate type
// ---------------------------------------------------------------------------
namespace {

const char* FLAT_COLOR_PREFS = "/color-editor";

class FlatColorEditor : public QWidget {
public:
    FlatColorEditor(Type space, std::shared_ptr<Inkscape::Colors::ColorSet> colors,
                    QWidget* parent = nullptr)
        : QWidget(parent)
        , _picker(ColorPickerPanel::create(space,
                      get_plate_type_preference(FLAT_COLOR_PREFS, ColorPickerPanel::Rect),
                      colors))
    {
        auto layout = new QVBoxLayout(this);
        layout->setContentsMargins(0, 0, 0, 0);
        layout->addWidget(_picker.get());
    }

    void setColorPickerPlate(ColorPickerPanel::PlateType type) {
        _picker->setPlateType(type);
        set_plate_type_preference(FLAT_COLOR_PREFS, type);
    }

    ColorPickerPanel::PlateType getColorPickerPlate() const {
        return _picker->getPlateType();
    }

    ColorPickerPanel& getPicker() { return *_picker; }

private:
    std::unique_ptr<ColorPickerPanel> _picker;
};

// ---------------------------------------------------------------------------
// Color-type helpers
// ---------------------------------------------------------------------------
Type get_color_type() {
    auto name = Inkscape::Preferences::get()->getString("/color-picker/sel-color-type", "HSL");
    auto space = Inkscape::Colors::Manager::get().find(std::string(name));
    return space ? space->getType() : Type::HSL;
}

void store_color_type(Type type) {
    if (auto space = Inkscape::Colors::Manager::get().find(type)) {
        Inkscape::Preferences::get()->setString("/color-picker/sel-color-type", space->getName());
    }
}

} // namespace

// ---------------------------------------------------------------------------
// PaintSelector base
// ---------------------------------------------------------------------------
PaintSelector::PaintSelector()
    : QWidget(nullptr)
{
    setObjectName("PaintSelector");
}

// ---------------------------------------------------------------------------
// PaintSelectorImpl — full implementation, hidden in this translation unit
// ---------------------------------------------------------------------------
class PaintSelectorImpl : public PaintSelector {
    Q_OBJECT
public:
    PaintSelectorImpl(bool support_no_paint, bool support_fill_rule, bool compact_mode, QWidget* parent);

    void setDesktop(SPDesktop* desktop) override {
        _desktop = desktop;
        // _swatch.set_desktop(desktop);
    }
    void setDocument(SPDocument* document) override {
        _document = document;
        _mesh.setDocument(document);
        // _swatch.setDocument(document);
        _pattern.setDocument(document);
    }
    void showPlaceholder(const QString& text, bool reset_toggles) override {
        _ui.placeholderLabel->setText(text);
        _ui.stack->setCurrentWidget(_ui.placeholderPage);
        _mode = PaintMode::None;
        if (reset_toggles) {
            auto scoped = _update.block();
            // Temporarily disable exclusivity so we can uncheck all buttons
            _mode_group->setExclusive(false);
            for (auto& [mode, btn] : _mode_buttons) {
                btn->setChecked(false);
            }
            _mode_group->setExclusive(true);
        }
        _ui.stack->updateGeometry();
    }

    // called from the outside to update UI
    void setMode(PaintMode mode) override;
    // internal handler for buttons switching paint mode
    void switch_paint_mode(PaintMode mode);
    void setColor(const Inkscape::Colors::Color& color) override;
    void updateFromPaint(const SPIPaint& paint) override;
    void updateFromPaintProps(const Linea::PaintProp& paint) override;
    void set_gradient(SPGradient* gradient, SPStop* selected_stop);
    void setFillRule(FillRule fill_rule) override;
    void _set_mode(PaintMode mode);

    void fire_flat_color_changed() {
        if (_update.pending()) return;
        Q_EMIT flatColorChanged(_color->getAverage());
    }
    // get selected pattern/hatch
    SPPaintServer* get_paint() {
        SPPaintServer* paint = nullptr;
        auto id = _pattern.getSelectedDocPattern();
        if (!id.empty() && _document) {
            paint = cast<SPPaintServer>(_document->getObjectById(id));
        }
        if (!paint) {
            auto [stock_id, stock_doc] = _pattern.getSelectedStockPattern();
            if (!stock_id.empty() && stock_doc) {
                std::string urn = "urn:inkscape:pattern:" + stock_id;
                paint = cast<SPPaintServer>(get_stock_item(_document, urn.c_str(), true, stock_doc));
            }
        }
        return paint;
    }
    void fire_pattern_changed() {
        if (_update.pending()) return;

        auto scoped = _update.block();
        auto paint = get_paint();
        if (auto pattern = cast<SPPattern>(paint)) {
            Q_EMIT patternChanged(pattern,
                _pattern.getSelectedColor(), QString::fromStdString(_pattern.getLabel()),
                _pattern.getSelectedTransform(), _pattern.getSelectedOffset(),
                _pattern.isSelectedScaleUniform(), _pattern.getSelectedGap());
        }
        else if (auto hatch = cast<SPHatch>(paint)) {
            Q_EMIT hatchChanged(hatch,
                _pattern.getSelectedColor(), QString::fromStdString(_pattern.getLabel()),
                _pattern.getSelectedTransform(), _pattern.getSelectedOffset(),
                _pattern.getSelectedPitch(), _pattern.getSelectedRotation(),
                _pattern.getSelectedThickness());
        }
    }
    void fire_gradient_changed(SPGradient* gradient, PaintMode mode) {
        if (_update.pending()) return;

        auto scoped = _update.block();
        auto* vector = gradient ? gradient->getVector() : nullptr;
        Q_EMIT gradientChanged(vector, _gradient.getType());
    }
    void fire_swatch_changed(SPGradient* swatch, EditOperation action, SPGradient* replacement,
                             std::optional<Color> color, QString label) {
        if (_update.pending()) return;

        auto scoped = _update.block();
        Q_EMIT swatchChanged(swatch, action, replacement, color, label);
    }
    void fire_mesh_changed(SPGradient* mesh) {
        if (_update.pending()) return;

        auto scoped = _update.block();
        Q_EMIT meshChanged(mesh);
    }

    // set current page color plate type
    void set_plate_type(ColorPickerPanel::PlateType type);
    std::optional<ColorPickerPanel::PlateType> get_plate_type(QWidget* page) const;

    // map each PaintMode to its editor page widget (built once in the constructor)
    std::map<PaintMode, QWidget*> _pages;

    std::shared_ptr<Inkscape::Colors::ColorSet> _color = std::make_shared<Inkscape::Colors::ColorSet>();

    Ui::PaintSelector _ui;

    std::map<PaintMode, QToolButton*> _mode_buttons;
    QButtonGroup* _mode_group = nullptr;
    std::map<ColorPickerPanel::PlateType, QToolButton*> _plate_buttons;

    // compact plate buttons
    std::unique_ptr<QMenu> _menu_popover;
    bool _use_compact_mode = false;
    PaintMode _mode = PaintMode::None;
    SPDocument* _document = nullptr;
    FlatColorEditor _flat_color{get_color_type(), _color};
    GradientEditor _gradient{"/gradient-editor", get_color_type(), true, false};
    PatternEditor _pattern{"/pattern-editor", Inkscape::PatternManager::get()};
    // SwatchEditor _swatch{get_color_type(), "/swatch-editor"};
    MeshEditor _mesh;
    PaintInherited _inherited;
    FillRule _fill_rule = FillRule::NonZero;
    OperationBlocker _update;
    SPDesktop* _desktop = nullptr;
};

PaintSelectorImpl::PaintSelectorImpl(bool support_no_paint, bool support_fill_rule, bool compact_mode, QWidget* parent)
    : PaintSelector()
    , _use_compact_mode(compact_mode)
{
    if (parent) setParent(parent);
    _ui.setupUi(this);

    setFixedWidth(220);

    if (!support_fill_rule) {
        _ui.fillRuleButton->hide();
    }
    _color->set(Color(0x000000ff));

    auto types_layout = qobject_cast<QHBoxLayout*>(_ui.typesWidget->layout());

    // add buttons switching paint mode
    auto* mode_group = new QButtonGroup(this);
    mode_group->setExclusive(true);
    _mode_group = mode_group;
    for (auto& i : paint_modes) {
        if (i.mode == PaintMode::None && !support_no_paint) continue;

        auto* btn = new QToolButton(this);
        btn->setIcon(QIcon::fromTheme(i.icon, QIcon(QString(":/icons/") + i.icon)));
        btn->setToolTip(tr(i.tip));
        btn->setCheckable(true);
        btn->setAutoRaise(true);
        btn->setAutoExclusive(false);
        mode_group->addButton(btn);
        const PaintMode mode = i.mode;
        connect(btn, &QToolButton::toggled, this, [=, this](bool checked) {
            if (checked && !_update.pending()) {
                switch_paint_mode(mode);
            }
        });
        types_layout->addWidget(btn);
        _mode_buttons[i.mode] = btn;
    }

    if (_use_compact_mode) {
        _ui.pickersWidget->hide();
        _ui.menuButton->show();
        _menu_popover = std::make_unique<QMenu>(this);
        _ui.menuButton->setMenu(_menu_popover.get());
    } else {
        _ui.menuButton->hide();
        _ui.pickersWidget->show();
    }

    static const struct {
        ColorPickerPanel::PlateType type;
        const char* icon;
        const char* label;
        const char* tooltip;
    } pickers[] = {
        {ColorPickerPanel::Rect,   "color-picker-rect",   _("Color Plane"),    _("Show color plane")},
        {ColorPickerPanel::Circle, "color-picker-circle", _("Color Wheel"),  _("Show color wheel")},
        {ColorPickerPanel::None,   "color-picker-input",  _("Only Sliders"), _("Show color sliders only")},
    };

    QToolButton* plate_btns[] = {_ui.rectButton, _ui.circleButton, _ui.inputButton};

    auto* plate_group = new QButtonGroup(this);
    plate_group->setExclusive(true);
    for (int idx = 0; idx < 3; ++idx) {
        const auto& p = pickers[idx];
        auto* pb = plate_btns[idx];
        pb->setIcon(QIcon::fromTheme(p.icon, QIcon(QString(":/icons/") + p.icon)));
        pb->setToolTip(tr(p.tooltip));
        pb->setCheckable(true);
        pb->setAutoRaise(true);
        pb->setAutoExclusive(false);
        plate_group->addButton(pb);
        _plate_buttons[p.type] = pb;

        if (_use_compact_mode) {
            auto* action = _menu_popover->addAction(
                QIcon::fromTheme(p.icon, QIcon(QString(":/icons/") + p.icon)),
                tr(p.label));
            action->setToolTip(tr(p.tooltip));
            connect(action, &QAction::triggered, this, [this, type = p.type, icon = p.icon] {
                if (!_update.pending()) {
                    set_plate_type(type);
                    _ui.menuButton->setIcon(
                        QIcon::fromTheme(icon, QIcon(QString(":/icons/") + icon)));
                }
            });
        } else {
            connect(pb, &QToolButton::toggled, this, [this, pb, type = p.type](bool checked) {
                if (checked && !_update.pending()) {
                    set_plate_type(type);
                }
            });
        }
    }

    _flat_color.getPicker().colorSpaceChanged().connect([](Type type) {
        store_color_type(type);
    });

    connect(&_mesh, &MeshEditor::changed, this,
        [this](SPGradient* mesh) { fire_mesh_changed(mesh); });
/*
    _swatch.signal_changed().connect([this](auto swatch, auto operation, auto replacement) {
        fire_swatch_changed(swatch, operation, replacement, {}, {});
    });
    _swatch.signal_color_changed().connect([this](auto swatch, auto& color) {
        fire_swatch_changed(swatch, EditOperation::Change, nullptr, color, {});
    });
    _swatch.signal_label_changed().connect([this](auto swatch, auto& label) {
        fire_swatch_changed(swatch, EditOperation::Rename, nullptr, {}, label);
    });
    _swatch.get_picker().colorSpaceChanged().connect([](Type type) {
        store_color_type(type);
    });
*/
    connect(_ui.fillRuleButton, &QToolButton::clicked, this, [this] {
        if (_update.pending()) return;

        auto scoped = _update.block();
        Q_EMIT fillRuleChanged(_fill_rule == FillRule::NonZero ? FillRule::EvenOdd : FillRule::NonZero);
    });
    // inherited paint variants
    connect(&_inherited, &PaintInherited::modeChanged, this, [this](PaintDerivedMode mode) {
        Q_EMIT inheritModeChanged(mode);
    });

    connect(&_gradient, &GradientEditor::signalChanged, this,
        [this](SPGradient* gradient) { fire_gradient_changed(gradient, _mode); });
    _gradient.setContentsMargins(0, 4, 0, 0);
    _gradient.getPicker().colorSpaceChanged().connect([](Type type) {
        store_color_type(type);
    });

    // force height to reveal a list of patterns:
    _pattern.setObjectName("PatternEditorPopup");
    connect(&_pattern, &PatternEditor::changed, this, [this] { fire_pattern_changed(); });
    connect(&_pattern, &PatternEditor::colorChanged, this, [this](auto) { fire_pattern_changed(); });
    connect(&_pattern, &PatternEditor::editRequested, this, [this] {
        if (_desktop) set_active_tool(_desktop, "Node");
    });
    _pattern.setContentsMargins(0, 4, 0, 0);

    _set_mode(PaintMode::None);

    _pages = {
        {PaintMode::Solid,        &_flat_color},
        {PaintMode::CssSwatch,    &_flat_color},
        {PaintMode::LegacySwatch, &_gradient},
        {PaintMode::Gradient,     &_gradient},
        {PaintMode::Pattern,      &_pattern},
        {PaintMode::Hatch,        &_pattern},
        {PaintMode::Mesh,         &_mesh},
        {PaintMode::Derived,      &_inherited},
    };
    for (auto [mode, child] : _pages) {
        if (child && mode != PaintMode::Hatch) {
            _ui.stack->addWidget(child);
        }
    }

    _color->signal_changed.connect([this] {
        fire_flat_color_changed();
    });
}

void PaintSelectorImpl::switch_paint_mode(PaintMode mode) {
    // fire mode change
    Q_EMIT modeChanged(mode);

    switch (mode) {
    case PaintMode::None:
        break;
    case PaintMode::Solid:
    case PaintMode::CssSwatch:
        fire_flat_color_changed();
        break;
    case PaintMode::Pattern:
    case PaintMode::Hatch:
        fire_pattern_changed();
        break;
    case PaintMode::Gradient:
        fire_gradient_changed(nullptr, mode);
        break;
    case PaintMode::Mesh:
        fire_mesh_changed(nullptr);
        break;
    case PaintMode::LegacySwatch:
        //todo: verify: .getGradientSelector()->getVector();
        // fire_swatch_changed(_swatch.get_selected_vector(), EditOperation::New, nullptr, {}, {});
        fire_gradient_changed(nullptr, mode);
        break;
    case PaintMode::Derived: {
        // Ensure a radio button is selected (default to Unset) and apply it
        auto mode = _inherited.getMode();
        _inherited.setMode(mode);
        Q_EMIT inheritModeChanged(mode);
        break;
    }
    default:
        assert(false);
        break;
    }

    setMode(mode);
}

void PaintSelectorImpl::setColor(const Inkscape::Colors::Color& color) {
    _color->set(color);
}

void PaintSelectorImpl::setMode(PaintMode mode) {
    if (mode == _mode) return;

    _set_mode(mode);
}

void PaintSelectorImpl::_set_mode(PaintMode mode) {
    _mode = mode;
    bool has_color_picker = false;

    // show the corresponding editor page
    if (auto it = _pages.find(mode); it != end(_pages)) {
        _ui.stack->setCurrentWidget(it->second);
        // sync plate type buttons with the current page
        auto type = get_plate_type(it->second);
        if (type.has_value()) {
            has_color_picker = true;
            if (auto it2 = _plate_buttons.find(*type); it2 != end(_plate_buttons)) {
                auto scoped = _update.block();
                it2->second->setChecked(true);
                if (_use_compact_mode) {
                    const char* icons[] = {"color-picker-rect", "color-picker-circle", "color-picker-input"};
                    _ui.menuButton->setIcon(
                        QIcon::fromTheme(icons[static_cast<int>(*type)],
                            QIcon(QString(":/icons/") + icons[static_cast<int>(*type)])));
                }
            }
        }
    }
    if (auto it = _mode_buttons.find(mode == PaintMode::Hatch ? PaintMode::Pattern : mode);
        it != end(_mode_buttons)) {
        auto scoped = _update.block();
        it->second->setChecked(true);
    }
    // color picker available?
    _ui.pickersWidget->setEnabled(has_color_picker);
    if (_use_compact_mode) {
        _ui.menuButton->setEnabled(has_color_picker);
    }

    // Notify parent layouts that our size may have changed (AdaptiveStack
    // reports the current page's size, not the tallest page).
    _ui.stack->updateGeometry();
}

void PaintSelectorImpl::set_plate_type(ColorPickerPanel::PlateType type) {
    if (auto it = _pages.find(_mode); it != end(_pages)) {
        auto page = it->second;

        if (page == &_flat_color) {
            _flat_color.setColorPickerPlate(type);
        }
        else if (page == &_gradient) {
            _gradient.setColorPickerPlate(type);
        }
        // else if (page == &_swatch) {
        //     _swatch.set_color_picker_plate(type);
        // }
    }
}

std::optional<ColorPickerPanel::PlateType> PaintSelectorImpl::get_plate_type(QWidget* page) const {
    if (page == &_flat_color) {
        return _flat_color.getColorPickerPlate();
    }
    else if (page == &_gradient) {
        return _gradient.getColorPickerPlate();
    }
    // else if (page == &_swatch) {
    //     return _swatch.get_color_picker_plate();
    // }

    return {};
}

void PaintSelectorImpl::set_gradient(SPGradient* gradient, SPStop* selected_stop) {
    auto vector = gradient->getVector();
    _gradient.setMode(is<SPLinearGradient>(gradient)
                      ? GradientSelectorInterface::MODE_LINEAR
                      : GradientSelectorInterface::MODE_RADIAL);
    _gradient.setGradient(gradient);
    _gradient.setVector(vector ? vector->document : nullptr, vector);
    _gradient.selectStop(selected_stop);
    if (vector) {
        _gradient.setUnits(vector->getUnits());
        _gradient.setSpread(vector->getSpread());
    }
}

void PaintSelectorImpl::updateFromPaint(const SPIPaint& paint) {
    auto scoped = _update.block();

    if (auto* server = paint.isPaintserver() ? paint.href->getObject() : nullptr) {
        if (is<SPGradient>(server) && cast<SPGradient>(server)->getVector()->isSwatch()) {
            // swatch color
            // auto vector = cast<SPGradient>(server)->getVector();
            // _swatch.select_vector(vector);
            auto* gradient = cast<SPGradient>(server);
            auto* stop = cast<SPStop>(const_cast<SPIPaint&>(paint).getTag());
            set_gradient(gradient, stop);
        }
        else if (is<SPLinearGradient>(server) || is<SPRadialGradient>(server)) {
            // normal gradient
            auto* gradient = cast<SPGradient>(server);
            auto* stop = cast<SPStop>(const_cast<SPIPaint&>(paint).getTag());
            set_gradient(gradient, stop);
        }
#ifdef WITH_MESH
        else if (is<SPMeshGradient>(server)) {
            // mesh
            auto* array = cast<SPGradient>(server)->getArray();
            _mesh.setSelectedMesh(array);
        }
#endif
        else if (is<SPPattern>(server)) {
            // pattern
            _pattern.setSelected(cast<SPPattern>(server));
        }
        else if (is<SPHatch>(server)) {
            // hatch
            _pattern.setSelected(cast<SPHatch>(server));
        }
    }
    else if (auto inherited = get_inherited_paint_mode(paint)) {
        _inherited.setMode(*inherited);
    }
}

void PaintSelectorImpl::updateFromPaintProps(const Linea::PaintProp& paint) {
    auto scoped = _update.block();

    setMode(paint.mode);

    switch (paint.mode) {
    case PaintMode::None:
        // no op
        break;
    case PaintMode::Solid:
    case PaintMode::CssSwatch:
        // set through setColor
        setColor(paint.color.value_or(Inkscape::Colors::Color(0x000000ff)));
        break;
    case PaintMode::Gradient:
        set_gradient(paint.gradient, paint.selected_stop);
        break;
    case PaintMode::LegacySwatch:
        // _swatch.select_vector(paint.swatch->getVector());
        // _pattern.setSelected(paint.swatch);
        break;
    case PaintMode::Pattern:
        _pattern.setSelected(paint.pattern);
        break;
    case PaintMode::Hatch:
        _pattern.setSelected(paint.hatch);
        break;
    case PaintMode::Mesh:
        _mesh.setSelectedMesh(paint.mesh);
        break;
    case PaintMode::Derived:
        _inherited.setMode(paint.derived_mode);
        break;
    default:
        g_warning("Unknown paint mode in updateFromPaintProps: %d", static_cast<int>(paint.mode));
        break;
    }
}

void PaintSelectorImpl::setFillRule(FillRule fill_rule) {
    _fill_rule = fill_rule;
    const char* icon = fill_rule == FillRule::NonZero ? "fill-rule-nonzero" : "fill-rule-even-odd";
    _ui.fillRuleButton->setIcon(QIcon::fromTheme(icon, QIcon(QString(":/icons/") + icon)));
}

std::unique_ptr<PaintSelector> PaintSelector::create(bool support_no_paint, bool support_fill_rule, bool compact_mode, QWidget* parent) {
    return std::make_unique<PaintSelectorImpl>(support_no_paint, support_fill_rule, compact_mode, parent);
}

} // namespace Linea::UI

#include "paint-selector.moc"
