// SPDX-License-Identifier: GPL-2.0-or-later
//
// Created by Michael Kowalski on 11/1/25.
//

#include "paint-inherited.h"

#include "ui_paint-inherited.h" // Generated by CMake AUTOUIC

#include <array>
#include <cstring>
#include <glibmm/i18n.h>

#include <QRadioButton>

namespace Linea::UI {

namespace {

// inherited paint variants
const std::array<std::pair<const char*, PaintDerivedMode>, 5> derived_paints = {
    std::pair{"paint-unset", PaintDerivedMode::Unset},
    {"paint-inherit",        PaintDerivedMode::Inherit},
    {"paint-context-stroke", PaintDerivedMode::ContextStroke},
    {"paint-context-fill",   PaintDerivedMode::ContextFill},
    {"paint-current-color",  PaintDerivedMode::CurrentColor}
};

} // namespace

PaintInherited::PaintInherited(QWidget* parent)
    : QWidget(parent)
    , _ui(std::make_unique<Ui::PaintInherited>())
{
    _ui->setupUi(this);
    setupConnections();
}

PaintInherited::~PaintInherited() = default;

void PaintInherited::setupConnections() {
    connect(_ui->paintUnset, &QRadioButton::toggled, this, &PaintInherited::onPaintUnsetToggled);
    connect(_ui->paintInherit, &QRadioButton::toggled, this, &PaintInherited::onPaintInheritToggled);
    connect(_ui->paintContextFill, &QRadioButton::toggled, this, &PaintInherited::onPaintContextFillToggled);
    connect(_ui->paintContextStroke, &QRadioButton::toggled, this, &PaintInherited::onPaintContextStrokeToggled);
    connect(_ui->paintCurrentColor, &QRadioButton::toggled, this, &PaintInherited::onPaintCurrentColorToggled);
}

void PaintInherited::onPaintUnsetToggled(bool checked) {
    if (checked && !_update.pending()) {
        Q_EMIT modeChanged(PaintDerivedMode::Unset);
    }
}

void PaintInherited::onPaintInheritToggled(bool checked) {
    if (checked && !_update.pending()) {
        Q_EMIT modeChanged(PaintDerivedMode::Inherit);
    }
}

void PaintInherited::onPaintContextFillToggled(bool checked) {
    if (checked && !_update.pending()) {
        Q_EMIT modeChanged(PaintDerivedMode::ContextFill);
    }
}

void PaintInherited::onPaintContextStrokeToggled(bool checked) {
    if (checked && !_update.pending()) {
        Q_EMIT modeChanged(PaintDerivedMode::ContextStroke);
    }
}

void PaintInherited::onPaintCurrentColorToggled(bool checked) {
    if (checked && !_update.pending()) {
        Q_EMIT modeChanged(PaintDerivedMode::CurrentColor);
    }
}

void PaintInherited::setMode(std::optional<PaintDerivedMode> maybe_mode) {
    auto scoped = _update.block();

    if (!maybe_mode) {
        // mode cannot be determined, is mixed, or does not apply; clear all radio buttons
        _ui->paintUnset->setChecked(false);
        _ui->paintInherit->setChecked(false);
        _ui->paintContextFill->setChecked(false);
        _ui->paintContextStroke->setChecked(false);
        _ui->paintCurrentColor->setChecked(false);
        return;
    }

    auto mode = maybe_mode.value();
    if (mode == PaintDerivedMode::Inherit) {
        // "inherit" keyword and unset paint are currently both represented by "from ancestor" button
        mode = PaintDerivedMode::Unset;
    }

    for (auto& [id, val] : derived_paints) {
        if (mode == val) {
            if (strcmp(id, "paint-unset") == 0) {
                _ui->paintUnset->setChecked(true);
            } else if (strcmp(id, "paint-inherit") == 0) {
                _ui->paintInherit->setChecked(true);
            } else if (strcmp(id, "paint-context-fill") == 0) {
                _ui->paintContextFill->setChecked(true);
            } else if (strcmp(id, "paint-context-stroke") == 0) {
                _ui->paintContextStroke->setChecked(true);
            } else if (strcmp(id, "paint-current-color") == 0) {
                _ui->paintCurrentColor->setChecked(true);
            }
            break;
        }
    }
}

PaintDerivedMode PaintInherited::getMode() const {
    if (_ui->paintUnset->isChecked()) {
        return PaintDerivedMode::Unset;
    } else if (_ui->paintInherit->isChecked()) {
        return PaintDerivedMode::Inherit;
    } else if (_ui->paintContextFill->isChecked()) {
        return PaintDerivedMode::ContextFill;
    } else if (_ui->paintContextStroke->isChecked()) {
        return PaintDerivedMode::ContextStroke;
    } else if (_ui->paintCurrentColor->isChecked()) {
        return PaintDerivedMode::CurrentColor;
    }

    g_warning("PaintInherited::get_mode - mode has not been set.");
    return PaintDerivedMode::Unset;
}

} // namespace Linea::UI
