// SPDX-License-Identifier: GPL-2.0-or-later
/**
 * @file
 * Text panel — font, typography and text decoration editor
 */

#include "text-panel.h"

#include <QComboBox>
#include <QPushButton>
#include <QSignalBlocker>
#include <QSizePolicy>
#include <utility>

#include "ui_text-panel.h" // Generated by CMake AUTOUIC
#include "color-picker.h"
#include "decoration-options.h"
#include "font-list.h"
#include "font-variations.h"
#include "number-edit.h"
#include "popup-menu.h"
#include "radio-toggle.h"
#include "unit-tracker.h"

#include "document.h"
#include "document-undo.h"
#include "object/sp-flowtext.h"
#include "preferences.h"
#include "props/binder.h"
#include "props/property-def.h"
#include "style.h"
#include "style-internal.h"
#include "text-editing.h"
#include "ui/tools/text-tool.h"
#include "util/cast.h"
#include "util/font-discovery.h"
#include "util/text-utils.h"
#include "util/units.h"

using Inkscape::DocumentUndo;
using Inkscape::FontDiscovery;
using Inkscape::FontInfo;
using Inkscape::Util::Quantity;
using Inkscape::Util::Unit;
using Inkscape::Util::UnitTable;

namespace Linea::UI {

namespace {

int unit_to_css_unit(const Unit* unit) {
    return Linea::unit_to_css_unit(unit);
}

} // namespace

TextPanel::TextPanel(QWidget* parent)
    : QWidget(parent)
    , _ui(std::make_unique<Ui::TextPanel>())
    , _tracker_fs(new UnitTracker(Inkscape::Util::UNIT_TYPE_LINEAR, this))
    , _tracker_lh(new UnitTracker(Inkscape::Util::UNIT_TYPE_LINEAR, this))
{
    _ui->setupUi(this);

    // Allow horizontal shrinking
    setMinimumWidth(0);
    setSizePolicy(QSizePolicy::Ignored, QSizePolicy::Preferred);

    // Decoration options popup (created in code; the widget is not in the .ui).
    // Must exist before setupConnections() wires its signals.
    _decorationOptions = new DecorationOptions(this);
    _decorationPopup = new PopupMenu(this);
    _decorationPopup->setContent(_decorationOptions);

    // Font browser popup (created in code; the widget is not in the .ui).
    _fontList = new FontList(this);
    _fontListPopup = new PopupMenu(this);
    _fontListPopup->setContent(_fontList);

    setupUnitTrackers();
    setupConnections();
    setupFontDiscovery();

    // Limit the variable-font axes area to about 4.5 axis rows;
    // when there are more than 4 axes, then 1/2 will indicate overflow.
    static int four = _ui->fontVariations->measureHeight(4);
    static int five = _ui->fontVariations->measureHeight(5);
    int row = five - four;
    _variableFontsMaxHeight = four + row * 0.65; // height tweaked to uncover just enough of the last row
}

TextPanel::~TextPanel() = default;

void TextPanel::setDocument(SPDocument* document) {
    _document = document;
}

void TextPanel::setDesktop(SPDesktop* desktop) {
    _desktop = desktop;
    // _cursor_moved.disconnect();
    // if (desktop) {
    //     _cursor_moved = desktop->connect_text_cursor_moved([this](Inkscape::UI::Tools::TextTool* tool) {
    //         if (tool && _current_item) {
    //             subselectionChanged(tool->get_subselection(false));
    //         }
    //     });
    // }
}

void TextPanel::setupUnitTrackers() {
    // Font-size tracker: restore saved unit (default to pt)
    {
        int fs_css = Preferences::get()->getInt("/options/font/unitType", SP_CSS_UNIT_PT);
        _tracker_fs->setActiveUnitByAbbr(sp_style_get_css_unit_string(fs_css));
    }
    _tracker_fs->attachCombo(_ui->fontSizeUnit);

    // Line-height tracker: add special units (same as text toolbar)
    auto lines = Unit::create("lines");
    _tracker_lh->prependUnit(std::move(lines));
    _tracker_lh->addUnit(UnitTable::get().getUnit("%"));
    _tracker_lh->addUnit(UnitTable::get().getUnit("em"));
    _tracker_lh->addUnit(UnitTable::get().getUnit("ex"));
    _tracker_lh->setActiveUnitByAbbr("lines");
    _tracker_lh->attachCombo(_ui->lineHeightUnit);

    // Update suffixes when unit changes
    connect(_tracker_fs, &UnitTracker::unitChanged, [this](const Unit* unit) {
        if (unit) _ui->fontSize->setSuffix(QString(" ") + QString::fromStdString(unit->abbr));
    });
    connect(_tracker_lh, &UnitTracker::unitChanged, [this](const Unit* unit) {
        if (unit) {
            _ui->lineHeight->setSuffix(unit->abbr.empty() ? QString() : QString(" ") + QString::fromStdString(unit->abbr));
        }
    });

    // Set initial suffixes
    if (auto u = _tracker_fs->getActiveUnit()) {
        _ui->fontSize->setSuffix(QString(" ") + QString::fromStdString(u->abbr));
    }
    if (auto u = _tracker_lh->getActiveUnit()) {
        _ui->lineHeight->setSuffix(u->abbr.empty() ? QString() : QString(" ") + QString::fromStdString(u->abbr));
    }

    // Font-size unit change: convert displayed value and save preference
    connect(_tracker_fs, &UnitTracker::unitChanged, [this](const Unit* unit) {
        if (!unit) return;
        Preferences::get()->setInt("/options/font/unitType", unit_to_css_unit(unit));
        updateTypographyState();
    });

    // Line-height unit change: convert displayed value between old/new units.
    //
    // TODO: When the binder pushes a new line_height value, it calls
    // tracker->setActiveUnitByAbbr() which triggers this handler. The handler
    // does a wasteful conversion using a stale _lineheight_unit, but the
    // binder's setValue() immediately overwrites the result — so the final
    // widget value is correct. _lineheight_unit is updated on line 175 below,
    // so it ends up in sync. A proper fix would distinguish user-initiated
    // unit changes from binder-initiated ones (e.g. via a flag or by checking
    // tracker->isUpdating() before the signal is emitted).
    connect(_tracker_lh, &UnitTracker::unitChanged, [this](const Unit* unit) {
printf("line height unit: %s - upd: %d\n", unit ? unit->abbr.c_str() : "null", _tracker_lh->isUpdating());
        if (!unit || !canUpdate()) return;

        int new_css = unit_to_css_unit(unit);
        if (_lineheight_unit == new_css) return;

        double font_size = 0;
        int count = 0;
        for (auto item : getQueryItems()) {
            if (item && item->style) { font_size += item->style->font_size.computed; ++count; }
        }
        font_size = count > 0 ? font_size / count : 20;

        double lh = Linea::convert_lineheight_between_units(_ui->lineHeight->value(), _lineheight_unit, unit, font_size);
        _lineheight_unit = new_css;
        _ui->lineHeight->setSingleStep(unit->abbr == "%" ? 1.0 : 0.1);

        QSignalBlocker b(_ui->lineHeight);
        _ui->lineHeight->setValue(lh);
    });
}

void TextPanel::setupConnections() {
    // Font browser popup
    connect(_ui->fontBrowserBtn, &QPushButton::clicked, [this]() {
        _fontList->setFonts(_font_families);
        if (auto* font = getSelectedFont()) {
            auto family = font->ff->get_name();
            auto face = font->face ? Inkscape::get_face_style(font->face->describe()) : Glib::ustring();
            auto spec = Inkscape::get_fontspec(family, face);
            _fontList->setCurrentFont(QString::fromUtf8(spec.c_str()));
        }
        // Make the font list as tall as the main window.
        if (auto top = window()) {
            _fontList->setMinimumHeight(top->height());
        }
        _fontList->setMinimumWidth(300);
        _fontListPopup->showBesideWidget(_ui->fontBrowserBtn);
    });
    connect(_fontList, &FontList::fontChanged, [this](const QString& fontspec) {
        if (!canUpdate()) return;
        // fontspec is "Family, Face" — extract the family portion to find the combo index.
        auto gspec = Glib::ustring(fontspec.toUtf8().constData());
        auto comma = gspec.find(',');
        auto family = comma != Glib::ustring::npos ? gspec.substr(0, comma) : gspec;
        int idx = findFamilyIndex(family);
        if (idx >= 0) {
            _ui->fontFamily->setCurrentIndex(idx);
        }
        _fontListPopup->hide();
    });

    // Font family, style and variations write sides are created in bind()
    // (tracked by the binder, routed through editor->set).

    // Kerning horizontal
    connect(_ui->kernHorz, &NumberEdit::valueChanged, [this](double new_dx) {
        if (!canUpdate()) return;
        if (Linea::apply_text_dx(getTextTool(), _desktop, new_dx)) {
            DocumentUndo::maybeDone(_document, "ttb:dx", RC_("Undo", "Text: Change horizontal kerning"), "draw-text");
        }
    });

    // Kerning vertical
    connect(_ui->kernVert, &NumberEdit::valueChanged, [this](double new_dy) {
        if (!canUpdate()) return;
        if (Linea::apply_text_dy(getTextTool(), _desktop, new_dy)) {
            DocumentUndo::maybeDone(_document, "ttb:dy", RC_("Undo", "Text: Change vertical kerning"), "draw-text");
        }
    });

    // Character rotation
    connect(_ui->charRotation, &NumberEdit::valueChanged, [this](double new_degrees) {
        if (!canUpdate()) return;
        if (Linea::apply_text_char_rotation(getTextTool(), _desktop, new_degrees)) {
            DocumentUndo::maybeDone(_document, "ttb:rotate", RC_("Undo", "Text: Rotate characters"), "draw-text");
        }
    });

    // RadioToggle button values — must be set before bind() is called.
    _ui->alignToggle->setButtonValues({0, 1, 2, 3});
    _ui->writingModeToggle->setButtonValues({0, 1, 2});
    _ui->orientationToggle->setButtonValues({0, 1, 2});
    _ui->directionToggle->setButtonValues({0, 1});

    // Decoration popover — shown as a popup below the "more" button.
    connect(_ui->decorationMoreButton, &QPushButton::clicked, [this]() {
        _decorationPopup->showBelowWidget(_ui->decorationMoreButton);
    });
}

void TextPanel::setupFontDiscovery() {
    _font_stream = FontDiscovery::get().connect_to_fonts([this](const FontDiscovery::MessageType& msg) {
        if (auto r = Async::Msg::get_result(msg)) {
            _font_families = **r;
            Inkscape::sort_font_families(_font_families, true);
            populateFamilies();
        }
        else if (auto p = Async::Msg::get_progress(msg)) {
            auto&& family = std::get<std::vector<FontInfo>>(*p);
            if (!family.empty()) {
                _font_families.push_back(family);
            }
        }
    });
}

// --- Declarative binding (property system) -----------------------------------

void TextPanel::bind(Props::Binder& binder) {
    // Font size — model is px, convert to/from display unit
    binder.bind(Props::font_size,
                Props::UnitEdit{_ui->fontSize, _tracker_fs, Props::UnitStrategy::ConvertFromPx});

    // Line height — model carries its own unit (em, %, px, ...), sync tracker
    binder.bind(Props::line_height,
                Props::UnitEdit{_ui->lineHeight, _tracker_lh, Props::UnitStrategy::PreserveLineHeightUnit});

    // Letter spacing, word spacing — plain doubles (px)
    binder.bind(Props::letter_spacing, _ui->letterSpacing);
    binder.bind(Props::word_spacing, _ui->wordSpacing);

    // Alignment — RadioToggle (int button index 0-3)
    binder.bind(Props::text_align, _ui->alignToggle);

    // Writing mode — RadioToggle (int button index 0-2)
    binder.bind(Props::writing_mode, _ui->writingModeToggle);

    // Text orientation — RadioToggle (int button index 0-2)
    binder.bind(Props::text_orientation, _ui->orientationToggle);

    // Direction — RadioToggle (int button index 0-1)
    binder.bind(Props::direction, _ui->directionToggle);

    // Superscript / subscript — checkable QPushButtons (bool)
    binder.bind(Props::superscript, _ui->superscriptButton);
    binder.bind(Props::subscript, _ui->subscriptButton);

    // Decoration line toggles — checkable QPushButtons (bool)
    binder.bind(Props::underline, _ui->underlineButton);
    binder.bind(Props::overline, _ui->overlineButton);
    binder.bind(Props::strikethrough, _ui->strikethroughButton);
    binder.bind(Props::decoration_spelling_error, _ui->syntaxErrorButton);

    // Decoration options (line style, thickness, color) — the widget owns
    // its own bind() that wires all three sub-properties.
    _decorationOptions->bind(binder);

    // Font family — push via bindField (maps family name to combo index).
    // The refresh runs under _update.block() so setCurrentIndex doesn't
    // re-trigger the write handlers below.
    binder.bindField(Props::Field::font_family, [this](const Props::SelectionState& s) {
        auto scoped = _update.block();
        if (s.typography.font_family.is_mixed()) {
            _ui->fontFamily->setCurrentIndex(-1);
            populateStyles(-1);
        } else if (s.typography.font_family.is_single()) {
            int idx = findFamilyIndex(s.typography.font_family.value());
            _ui->fontFamily->setCurrentIndex(idx);
            populateStyles(idx);
        }
    });

    // Font style — push via bindField (maps style name to combo index).
    binder.bindField(Props::Field::font_style, [this](const Props::SelectionState& s) {
        auto scoped = _update.block();
        if (s.typography.font_style.is_mixed()) {
            _ui->fontStyle->setCurrentIndex(-1);
        } else if (s.typography.font_style.is_single()) {
            int idx = findStyleIndex(s.typography.font_style.value());
            if (idx >= 0) _ui->fontStyle->setCurrentIndex(idx);
        }
    });

    // Font family — write side. apply_font_family resolves the family in the
    // font database and preserves each item's current face where possible;
    // unknown names (combo edit text) are written as-is. The model refresh
    // that follows repopulates the style combo and the variations widget.
    binder.track(connect(_ui->fontFamily, QOverload<int>::of(&QComboBox::currentIndexChanged),
        [this, editor = binder.editor()](int idx) {
            if (_update.pending() || editor->busy()) return;
            auto family = idx >= 0 && idx < static_cast<int>(_family_names.size())
                ? _family_names[idx]
                : Glib::ustring(_ui->fontFamily->currentText().toUtf8().constData());
            if (!family.empty()) {
                editor->set(Props::font_family, family);
            }
        }));

    // Font variations — push via bindField.
    // The variations widget depends on both the font family (which axes exist)
    // and the font-variation-settings (the axis values). A variable font using
    // default axes has no font-variation-settings in its style, so switching
    // family to such a font leaves Field::font_variation unchanged — the
    // refresh must also fire on Field::font_family. Registration order matters:
    // the family bindField above runs first and updates the combo, so
    // getSelectedFont() here reads the already-correct family.
    auto refreshVariations = [this](const Props::SelectionState& s) {
        if (s.typography.font_variation.is_mixed() || s.typography.font_family.is_mixed()) {
            updateFontVariants(nullptr);
        } else if (s.typography.font_variation.is_single()) {
            const auto& fontspec = s.typography.font_family.value();
            if (s.typography.font_variation.value().axes.empty()) {
                updateFontVariants(getSelectedFont());
            } else {
                _ui->fontVariations->update(fontspec, &s.typography.font_variation.value());
            }
            _ui->fontVariationsScroll->setVisible(_ui->fontVariations->variationsPresent());
        }
    };
    binder.bindField(Props::Field::font_variation, refreshVariations);
    binder.bindField(Props::Field::font_family, refreshVariations);

    // Font variations — write side. User edits to axis sliders/spins are
    // read back via get_variations() and pushed through the editor.
    binder.track(connect(_ui->fontVariations, &FontVariations::changed,
        [this, editor = binder.editor()]() {
            if (_update.pending() || editor->busy()) return;
            editor->set(Props::font_variation, _ui->fontVariations->get_variations());
        }));

    // Font style — write side. apply_font_style resolves the face against
    // each item's own family, so mixed-family selections behave sensibly.
    binder.track(connect(_ui->fontStyle, QOverload<int>::of(&QComboBox::currentIndexChanged),
        [this, editor = binder.editor()](int) {
            if (_update.pending() || editor->busy()) return;
            auto style_name = Glib::ustring(_ui->fontStyle->currentText().toUtf8().constData());
            if (!style_name.empty()) {
                editor->set(Props::font_style, style_name);
            }
    }));

    // Orientation toggle is only meaningful in vertical writing mode —
    // hide it entirely for horizontal text.
    binder.visibleWhen(_ui->orientationToggle, [](const Props::SelectionState& s) {
        if (!s.typography.writing_mode.is_single()) return false;
        auto wm = s.typography.writing_mode.value();
        return wm == 1 || wm == 2;  // TB_RL or TB_LR (button indices)
    });

    // Writing mode and direction are object-level properties that don't
    // apply to text-span subselections — disable them when the text tool
    // has an active span subselection.
    binder.enableWhen(_ui->writingModeToggle, Props::Cond::noTextSubselection);
    binder.enableWhen(_ui->directionToggle, Props::Cond::noTextSubselection);

    // Header text — driven by tool/subselection state from the model.
    binder.bindField(Props::Field::counts, [this](const Props::SelectionState& s) {
        if (s.element.count.has_text_subselection) {
            _ui->textHeader->setText(tr("Selected text"));
        } else if (s.element.count.text_tool_active) {
            _ui->textHeader->setText(tr("Text characters"));
        } else {
            _ui->textHeader->setText(tr("Text element"));
        }
    });

    // Show panel when there are only textual items selected
    binder.visibleWhen(this, Props::Cond::allOf<&Props::Counts::textual>);
}

std::vector<SPItem*> TextPanel::getSubselection() {
    if (auto tool = getTextTool()) {
        return tool->get_subselection(true);
    }
    return Linea::get_all_text_spans(_current_item);
}

std::vector<SPItem*> TextPanel::getQueryItems() {
    auto spans = getSubselection();
    if (!spans.empty()) return spans;

    if (_current_item) {
        std::vector<SPItem*> items(1, _current_item);
        return items;
    }
    return {};
}

Inkscape::UI::Tools::TextTool* TextPanel::getTextTool() {
    if (!_desktop) return nullptr;
    return dynamic_cast<Inkscape::UI::Tools::TextTool*>(_desktop->getTool());
}

bool TextPanel::canUpdate() const {
    return !_update.pending() && _current_item && _document;
}

void TextPanel::updateTypographyState() {
    auto scoped = _update.block();

    auto items = getQueryItems();
    if (items.empty()) return;

    auto state = Linea::query_text_properties(items);

    updateTypographyState(state, getTextTool());
}

void TextPanel::updateTypographyState(const TypographyState& state, Inkscape::UI::Tools::TextTool* text_tool) {
    // Font family, style and variations are now pushed by bindField in bind().
    // Only kerning, rotation and flow-text sensitivities remain here.
    //
    // TODO: This old code path (via query_text_properties) coexists with the
    // binder's SelectionStateModel path. Both fire on selection/style changes.
    // They don't conflict (different widgets), but the old path is redundant
    // for bound properties and should eventually be removed once the binder
    // can handle kerning/rotation (which need text-tool cursor state, not
    // item CSS) and flow-text sensitivities (which need item type checks).

    // Dx, Dy, rotation
    _ui->kernHorz->setValue(Linea::query_text_dx(text_tool).value_or(0));
    _ui->kernVert->setValue(Linea::query_text_dy(text_tool).value_or(0));
    _ui->charRotation->setValue(Linea::query_text_char_rotation(text_tool).value_or(0));

    // Flow text sensitivities
    bool is_flow = is<SPFlowtext>(_current_item) || !is_kerning_supported(_current_item);
    _ui->alignToggle->setButtonEnabled(3, is_flow);
    _ui->kernHorz->setEnabled(!is_flow && text_tool != nullptr);
    _ui->kernVert->setEnabled(!is_flow && text_tool != nullptr);
    _ui->kerningLabel->setEnabled(!is_flow && text_tool != nullptr);
    _ui->charRotation->setEnabled(!is_flow && text_tool != nullptr);
    _ui->rotationLabel->setEnabled(!is_flow && text_tool != nullptr);
}

void TextPanel::populateFamilies() {
    QSignalBlocker b(_ui->fontFamily);
    _ui->fontFamily->clear();
    _family_names.clear();

    for (auto& family : _font_families) {
        auto& regular = Inkscape::get_family_font(family);
        auto name = regular.ff->get_name();
        _family_names.push_back(name);
        _ui->fontFamily->addItem(QString::fromUtf8(name.c_str()));
    }
}

void TextPanel::populateStyles(int family_data_index) {
    if (family_data_index == _style_index) return;
    _style_index = family_data_index;

    QSignalBlocker b(_ui->fontStyle);
    _ui->fontStyle->clear();
    _style_names.clear();

    if (family_data_index >= 0 && family_data_index < static_cast<int>(_font_families.size())) {
        auto& family = _font_families[family_data_index];
        for (auto& font : family) {
            if (font.face) {
                auto style = Inkscape::get_face_style(font.face->describe());
                _style_names.push_back(style);
                _ui->fontStyle->addItem(QString::fromUtf8(style.c_str()));
            }
        }
    } else {
        static const char* default_styles[] = {"Normal", "Italic", "Bold", "Bold Italic"};
        for (auto s : default_styles) {
            _style_names.emplace_back(s);
            _ui->fontStyle->addItem(QString::fromUtf8(s));
        }
    }
}

void TextPanel::updateFontVariants(const FontInfo* font) {
    if (!font) {
        _ui->fontVariations->update({});
        _ui->fontVariationsScroll->setVisible(false);
    } else {
        auto fontspec = Inkscape::get_inkscape_fontspec(font->ff, font->face, Glib::ustring());
        _ui->fontVariations->update(fontspec);
        int content = _ui->fontVariations->measureHeight();
        int cap = _variableFontsMaxHeight;
        _ui->fontVariationsScroll->setFixedHeight(std::min(content, cap));
        _ui->fontVariationsScroll->setVisible(_ui->fontVariations->variationsPresent());
    }
}

int TextPanel::findFamilyIndex(const Glib::ustring& name) const {
    auto lower = name.lowercase();
    for (int i = 0; i < static_cast<int>(_family_names.size()); ++i) {
        if (_family_names[i].lowercase() == lower) return i;
    }
    return -1;
}

int TextPanel::findStyleIndex(const Glib::ustring& name) const {
    auto lower = name.lowercase();
    for (int i = 0; i < static_cast<int>(_style_names.size()); ++i) {
        if (_style_names[i].lowercase() == lower) return i;
    }
    return -1;
}

const FontInfo* TextPanel::getSelectedFont() const {
    return findFontByStyle(Glib::ustring(_ui->fontStyle->currentText().toUtf8().constData()));
}

const FontInfo* TextPanel::findFontByStyle(const Glib::ustring& style_name) const {
    auto index = _ui->fontFamily->currentIndex();
    if (index >= 0 && index < static_cast<int>(_font_families.size())) {
        auto& family = _font_families[index];
        if (auto* font = Inkscape::find_font_face(family, style_name)) {
            return font;
        }
        return &Inkscape::get_family_font(family);
    }
    return nullptr;
}

} // namespace Linea::UI
