// SPDX-License-Identifier: GPL-2.0-or-later
/**
 * @file
 * Trace panel implementation.
 */

#include "trace-panel.h"

#include <QCheckBox>
#include <QComboBox>
#include <QLabel>
#include <QProgressBar>
#include <QPushButton>
#include <QRadioButton>
#include <QStackedWidget>
#include <algorithm>

#include "spin-scale.h"
#include "switch-widget.h"
#include "tab-strip.h"
#include "number-edit.h"
#include "trace/autotrace/inkscape-autotrace.h"
#include "trace/depixelize/inkscape-depixelize.h"
#include "trace/potrace/inkscape-potrace.h"

// Generated by UIC from trace-panel.ui
#include "ui_trace-panel.h"

namespace Linea::UI {

namespace {

/// Set every SpinScale's NumberEdit to the same minimum width (the widest
/// among the group), so the numeric fields line up visually.
void unifyNumberEditWidths(std::initializer_list<Linea::UI::SpinScale*> scales) {
    int maxW = 0;
    for (auto ss : scales) {
        maxW = std::max(maxW, ss->numberEdit()->sizeHint().width());
    }
    for (auto ss : scales) {
        ss->numberEdit()->setMinimumWidth(maxW);
    }
}

constexpr auto cbt_ss_map = std::to_array(
    {Trace::Potrace::TraceType::BRIGHTNESS, Trace::Potrace::TraceType::CANNY, Trace::Potrace::TraceType::QUANT,
     Trace::Potrace::TraceType::AUTOTRACE_SINGLE, Trace::Potrace::TraceType::AUTOTRACE_CENTERLINE});

constexpr auto cbt_ms_map =
    std::to_array({Trace::Potrace::TraceType::BRIGHTNESS_MULTI, Trace::Potrace::TraceType::QUANT_COLOR,
                   Trace::Potrace::TraceType::QUANT_MONO, Trace::Potrace::TraceType::AUTOTRACE_MULTI});

enum class EngineType { Potrace, Autotrace, Depixelize };

enum class Page { SingleScan, MultiScan, PixelArt };

} // namespace

TracePanel::TracePanel(QWidget* parent)
    : QWidget(parent)
    , _ui(std::make_unique<Ui::TracePanel>()) {
    _ui->setupUi(this);

    // Set up TabStrip with 3 tabs
    _ui->tabStrip->setAlignment(TabStrip::Alignment::Center);
    _ui->tabStrip->setShowCloseButton(false);
    _ui->tabStrip->addTab(tr("Single scan"), QString());
    _ui->tabStrip->addTab(tr("Multicolor"), QString());
    _ui->tabStrip->addTab(tr("Pixel art"), QString());
    _ui->tabStrip->setShowLabels(Linea::UI::TabStrip::ShowLabels::Always);
    _ui->tabStrip->selectTabAt(0);

    // Wire tab strip to stacked widget
    connect(_ui->tabStrip, &Linea::UI::TabStrip::tabSelectRequested, this, &TracePanel::onTabChanged);

    // Wire buttons
    connect(_ui->applyButton, &QPushButton::clicked, this, &TracePanel::onApplyClicked);
    connect(_ui->abortButton, &QPushButton::clicked, this, &TracePanel::onAbortClicked);
    connect(_ui->resetButton, &QPushButton::clicked, this, &TracePanel::onResetClicked);
    connect(_ui->updatePreviewButton, &QPushButton::clicked, this, [this] { requestPreview(); });

    // Wire live preview checkbox
    connect(_ui->livePreview, &QCheckBox::toggled, this, [this](bool enabled) {
        Q_EMIT livePreviewChanged(enabled);
        if (enabled) requestPreview();
    });

    // Wire parameter changes to trigger preview
    connect(_ui->CBT_SS, &QComboBox::currentIndexChanged, this, [this] {
        adjustParamsVisible();
        onParamsChanged();
    });
    connect(_ui->CBT_MS, &QComboBox::currentIndexChanged, this, &TracePanel::onParamsChanged);

    for (auto ss : {_ui->SS_BC_T, _ui->SS_ED_T, _ui->SS_CQ_T, _ui->SS_AT_FI_T, _ui->SS_AT_ET_T, _ui->speckles,
                    _ui->smooth, _ui->optimize, _ui->MS_scans, _ui->speckles_ms, _ui->smooth_ms, _ui->optimize_ms,
                    _ui->PA_curves, _ui->PA_islands, _ui->PA_sparse1, _ui->PA_sparse2}) {
        connect(ss, &Linea::UI::SpinScale::valueChanged, this, &TracePanel::onParamsChanged);
    }

    for (auto cb : {_ui->CB_invert, _ui->CB_MS_rb, _ui->CB_PA_optimize, _ui->CB_SIOX, _ui->CB_SIOX1}) {
        connect(cb, &QCheckBox::toggled, this, &TracePanel::onParamsChanged);
    }

    // Switches enable/disable their SpinScale
    auto bindSwitch = [this](QAbstractButton* sw, Linea::UI::SpinScale* ss) {
        ss->setEnabled(sw->isChecked());
        connect(sw, &QAbstractButton::toggled, this, [this, ss, sw](bool on) {
            ss->setEnabled(on);
            onParamsChanged();
        });
    };
    bindSwitch(_ui->CB_speckles, _ui->speckles);
    bindSwitch(_ui->CB_smooth, _ui->smooth);
    bindSwitch(_ui->CB_optimize, _ui->optimize);
    bindSwitch(_ui->CB_speckles1, _ui->speckles_ms);
    bindSwitch(_ui->CB_smooth1, _ui->smooth_ms);
    bindSwitch(_ui->CB_optimize1, _ui->optimize_ms);

    adjustParamsVisible();

    // Set initial values — onResetClicked() is the single source of truth
    onResetClicked();

    // Unify NumberEdit widths within each page so fields line up
    unifyNumberEditWidths({_ui->SS_BC_T, _ui->SS_ED_T, _ui->SS_CQ_T, _ui->SS_AT_FI_T, _ui->SS_AT_ET_T,
                           _ui->speckles, _ui->smooth, _ui->optimize});
    unifyNumberEditWidths({_ui->MS_scans, _ui->speckles_ms, _ui->smooth_ms, _ui->optimize_ms});
    unifyNumberEditWidths({_ui->PA_curves, _ui->PA_islands, _ui->PA_sparse1, _ui->PA_sparse2});
}

TracePanel::~TracePanel() = default;

void TracePanel::setImage(Trace::BitmapView bmp) {
    _bmp = bmp;
    requestPreview();
}

void TracePanel::setSioxMask(Cairo::RefPtr<Cairo::ImageSurface> mask) {
    _sioxMask = std::move(mask);
}

bool TracePanel::livePreviewEnabled() const {
    return _ui->livePreview->isChecked();
}

std::unique_ptr<Trace::TracingEngine> TracePanel::takeEngine() {
    return buildTraceConfig().engine;
}

bool TracePanel::sioxEnabled() const {
    auto current_page = static_cast<Page>(_ui->pageStack->currentIndex());
    auto& cb_siox = current_page == Page::SingleScan ? _ui->CB_SIOX : _ui->CB_SIOX1;
    return cb_siox->isChecked();
}

void TracePanel::setPreview(QImage image) {
    if (image.isNull()) {
        _ui->previewArea->setText(tr("No preview"));
        _ui->previewArea->setPixmap({});
    } else {
        _ui->previewArea->setPixmap(
            QPixmap::fromImage(image).scaled(_ui->previewArea->size(), Qt::KeepAspectRatio, Qt::SmoothTransformation));
    }
}

void TracePanel::setTraceProgress(double fraction) {
    _ui->progressBar->setValue(static_cast<int>(fraction * 100));
}

void TracePanel::setTraceComplete() {
    _tracing = false;
    _ui->progressBar->setValue(100);
    _ui->actionStack->setCurrentWidget(_ui->actionIdle);
}

void TracePanel::onApplyClicked() {
    if (_tracing) return;

    _tracing = true;
    _ui->progressBar->setValue(0);
    _ui->actionStack->setCurrentWidget(_ui->actionBusy);
    Q_EMIT traceRequested();
}

void TracePanel::onAbortClicked() {
    if (!_tracing) return;
    _tracing = false;
    _ui->actionStack->setCurrentWidget(_ui->actionIdle);
    Q_EMIT traceAborted();
}

void TracePanel::onResetClicked() {
    _ui->SS_BC_T->setValue(0.45);
    _ui->SS_ED_T->setValue(0.65);
    _ui->SS_CQ_T->setValue(64);
    _ui->SS_AT_FI_T->setValue(4);
    _ui->SS_AT_ET_T->setValue(2);
    _ui->MS_scans->setValue(8);
    _ui->PA_curves->setValue(1);
    _ui->PA_islands->setValue(5);
    _ui->PA_sparse1->setValue(4);
    _ui->PA_sparse2->setValue(1);
    _ui->speckles->setValue(2);
    _ui->smooth->setValue(1);
    _ui->optimize->setValue(0.2);
    _ui->speckles_ms->setValue(2);
    _ui->smooth_ms->setValue(1);
    _ui->optimize_ms->setValue(0.2);
    _ui->CB_invert->setChecked(false);
    _ui->CB_MS_smooth->setChecked(true);
    _ui->CB_MS_stack->setChecked(true);
    _ui->CB_MS_rb->setChecked(false);
    _ui->CB_speckles->setChecked(true);
    _ui->CB_smooth->setChecked(true);
    _ui->CB_optimize->setChecked(true);
    _ui->CB_speckles1->setChecked(true);
    _ui->CB_smooth1->setChecked(true);
    _ui->CB_optimize1->setChecked(true);
    _ui->CB_PA_optimize->setChecked(false);
    _ui->CB_SIOX->setChecked(false);
    _ui->CB_SIOX1->setChecked(false);
}

void TracePanel::onTabChanged(QWidget* tab) {
    if (!tab) return;

    int idx = _ui->tabStrip->getTabPosition(*tab);
    _ui->tabStrip->selectTab(*tab);
    _ui->pageStack->setCurrentIndex(idx);
    onParamsChanged();
}

void TracePanel::onParamsChanged() {
    if (_ui->livePreview->isChecked()) {
        requestPreview();
    }
}

void TracePanel::requestPreview() {
    if (_bmp.pixels == nullptr) return;
    Q_EMIT previewRequested();
}

void TracePanel::adjustParamsVisible() {
    int option = _ui->CBT_SS->currentIndex();
    if (option < 0) return;

    // Modes: 0=Brightness, 1=Canny(edge), 2=Quant, 3=Autotrace, 4=Centerline(autotrace)
    bool showBrightness = (option == 0);
    bool showEdge = (option == 1);
    bool showColors = (option == 2);
    bool showAutotrace = (option >= 3);

    _ui->ssBrightnessLabel->setVisible(showBrightness);
    _ui->SS_BC_T->setVisible(showBrightness);

    _ui->ssEdgeLabel->setVisible(showEdge);
    _ui->SS_ED_T->setVisible(showEdge);

    _ui->ssColorsLabel->setVisible(showColors);
    _ui->SS_CQ_T->setVisible(showColors);

    _ui->ssFilterIterLabel->setVisible(showAutotrace);
    _ui->SS_AT_FI_T->setVisible(showAutotrace);

    _ui->ssErrorLabel->setVisible(showAutotrace);
    _ui->SS_AT_ET_T->setVisible(showAutotrace);
}

TracePanel::TraceConfig TracePanel::buildTraceConfig() const {
    auto current_page = static_cast<Page>(_ui->pageStack->currentIndex());

    bool enable_siox = (current_page == Page::SingleScan ? _ui->CB_SIOX : _ui->CB_SIOX1)->isChecked();

    auto trace_type = current_page == Page::SingleScan ? cbt_ss_map.at(_ui->CBT_SS->currentIndex())
                                                       : cbt_ms_map.at(_ui->CBT_MS->currentIndex());

    EngineType engine_type;
    if (current_page == Page::PixelArt) {
        engine_type = EngineType::Depixelize;
    } else {
        switch (trace_type) {
            case Trace::Potrace::TraceType::AUTOTRACE_SINGLE:
            case Trace::Potrace::TraceType::AUTOTRACE_CENTERLINE:
            case Trace::Potrace::TraceType::AUTOTRACE_MULTI:
                engine_type = EngineType::Autotrace;
                break;
            default:
                engine_type = EngineType::Potrace;
                break;
        }
    }

    TraceConfig config;
    config.sioxEnabled = enable_siox;

    if (engine_type == EngineType::Potrace) {
        auto& cb_optimize = current_page == Page::SingleScan ? _ui->CB_optimize : _ui->CB_optimize1;
        auto& cb_smooth = current_page == Page::SingleScan ? _ui->CB_smooth : _ui->CB_smooth1;
        auto& cb_speckles = current_page == Page::SingleScan ? _ui->CB_speckles : _ui->CB_speckles1;
        auto& optimize_ss = current_page == Page::SingleScan ? _ui->optimize : _ui->optimize_ms;
        auto& smooth_ss = current_page == Page::SingleScan ? _ui->smooth : _ui->smooth_ms;
        auto& speckles_ss = current_page == Page::SingleScan ? _ui->speckles : _ui->speckles_ms;

        auto eng = std::make_unique<Trace::Potrace::PotraceTracingEngine>(
            trace_type, _ui->CB_invert->isChecked(), static_cast<int>(_ui->SS_CQ_T->value()), _ui->SS_BC_T->value(),
            0.0, _ui->SS_ED_T->value(), static_cast<int>(_ui->MS_scans->value()), _ui->CB_MS_stack->isChecked(),
            _ui->CB_MS_smooth->isChecked(), _ui->CB_MS_rb->isChecked());

        eng->setOptiCurve(cb_optimize->isChecked());
        eng->setOptTolerance(optimize_ss->value());
        eng->setAlphaMax(cb_smooth->isChecked() ? smooth_ss->value() : 0);
        eng->setTurdSize(cb_speckles->isChecked() ? static_cast<int>(speckles_ss->value()) : 0);

        config.engine = std::move(eng);
    } else if (engine_type == EngineType::Autotrace) {
        auto eng = std::make_unique<Trace::Autotrace::AutotraceTracingEngine>();

        switch (trace_type) {
            case Trace::Potrace::TraceType::AUTOTRACE_SINGLE:
                eng->setColorCount(2);
                break;
            case Trace::Potrace::TraceType::AUTOTRACE_CENTERLINE:
                eng->setColorCount(2);
                eng->setCenterLine(true);
                eng->setPreserveWidth(true);
                break;
            case Trace::Potrace::TraceType::AUTOTRACE_MULTI:
                eng->setColorCount(static_cast<int>(_ui->MS_scans->value()) + 1);
                break;
            default:
                break;
        }

        eng->setFilterIterations(static_cast<int>(_ui->SS_AT_FI_T->value()));
        eng->setErrorThreshold(_ui->SS_AT_ET_T->value());

        config.engine = std::move(eng);
    } else { // Depixelize
        auto eng = std::make_unique<Trace::Depixelize::DepixelizeTracingEngine>(
            _ui->RB_PA_voronoi->isChecked() ? Trace::Depixelize::TraceType::VORONOI
                                            : Trace::Depixelize::TraceType::BSPLINES,
            _ui->PA_curves->value(), static_cast<int>(_ui->PA_islands->value()),
            static_cast<int>(_ui->PA_sparse1->value()), _ui->PA_sparse2->value(), _ui->CB_PA_optimize->isChecked());

        config.engine = std::move(eng);
    }

    return config;
}

} // namespace Linea::UI
