// SPDX-License-Identifier: GPL-2.0-or-later
/**
 * @file
 * PdfImportDialog — Qt implementation.
 *
 * Replaces the GTK-based Inkscape::Extension::Internal::PdfImportDialog.
 * All widgets are defined in pdf-import-dialog.ui; this file only wires
 * up signals, populates models, and handles preview rendering.
 */

#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include <QCheckBox>
#include <QComboBox>
#include <QDialog>
#include <QDialogButtonBox>
#include <QDir>
#include <QFileInfo>
#include <QGroupBox>
#include <QIcon>
#include <QLabel>
#include <QLineEdit>
#include <QMessageBox>
#include <QPushButton>
#include <QSignalBlocker>
#include <QSlider>
#include <QStandardItemModel>
#include <QTabWidget>
#include <QTreeView>
#include <QUrl>
#include <algorithm>
#include <cmath>
#include <memory>
#include <Catalog.h>
#include <GfxFont.h>
#include <PDFDoc.h>
#include <Page.h>
#include <glibmm/i18n.h>
#include <goo/GooString.h>

#include "pdf-import-dialog.h"
#include "pdf-preview-area.h"

#ifdef HAVE_POPPLER_CAIRO
#include <cairo.h>
#include <glib/poppler.h>
#include <goo/gmem.h>
#endif

#include "async/async.h"
#include "async/channel.h"
#include "extension/input.h"
#include "extension/internal/pdfinput/pdf-parser.h"
#include "extension/internal/pdfinput/svg-builder.h"
#include "ui/util.h"
#include "util/gobjectptr.h"
#include "util/parse-int-range.h"

// Generated by UIC from pdf-import-dialog.ui
#include "ui_pdf-import-dialog.h"

namespace Linea::UI {

namespace {

/// Convert a FontStrategy preference string to the enum value.
FontStrategy pref_to_font_strategy(const std::string& value) {
    if (value == "render-missing") return FontStrategy::RENDER_MISSING;
    if (value == "substitute") return FontStrategy::SUBSTITUTE_MISSING;
    if (value == "keep-missing") return FontStrategy::KEEP_MISSING;
    if (value == "delete-missing") return FontStrategy::DELETE_MISSING;
    if (value == "render-all") return FontStrategy::RENDER_ALL;
    if (value == "delete-all") return FontStrategy::DELETE_ALL;
    qWarning("Unknown fontRendering option '%s'", value.c_str());
    return FontStrategy::SUBSTITUTE_MISSING;
}

/// Strategy combo entries (id, label) for the per-font combo box.
struct StrategyEntry {
    int id;
    const char* label;
};
const StrategyEntry kStrategyEntries[] = {
    {static_cast<int>(FontFallback::DELETE_TEXT), QT_TRANSLATE_NOOP("PdfImport", "Delete Text")},
    {static_cast<int>(FontFallback::AS_SHAPES), QT_TRANSLATE_NOOP("PdfImport", "Draw to Shapes")},
    {static_cast<int>(FontFallback::AS_TEXT), QT_TRANSLATE_NOOP("PdfImport", "Keep Original Font Name")},
    {static_cast<int>(FontFallback::AS_SUB), QT_TRANSLATE_NOOP("PdfImport", "Use Substitute Font")},
};

/// Precision labels evenly dividing the slider range.
const char* const kPrecisionLabels[] = {
    QT_TRANSLATE_NOOP("PdfImport", "rough"),
    QT_TRANSLATE_NOOP("PdfImport", "medium"),
    QT_TRANSLATE_NOOP("PdfImport", "fine"),
    QT_TRANSLATE_NOOP("PdfImport", "very fine"),
};

/// Combo box entry with an ID string and a translatable label.
struct ComboEntry {
    const char* id;
    const char* label;
};

const ComboEntry kClipToEntries[] = {
    {"none", QT_TRANSLATE_NOOP("PdfImport", "None")},
    {"media-box", QT_TRANSLATE_NOOP("PdfImport", "Media Box")},
    {"crop-box", QT_TRANSLATE_NOOP("PdfImport", "Crop Box")},
    {"trim-box", QT_TRANSLATE_NOOP("PdfImport", "Trim Box")},
    {"bleed-box", QT_TRANSLATE_NOOP("PdfImport", "Bleed Box")},
    {"art-box", QT_TRANSLATE_NOOP("PdfImport", "Art Box")},
};

const ComboEntry kGroupByEntries[] = {
    {"by-xobject", QT_TRANSLATE_NOOP("PdfImport", "PDF Object")},
    {"by-layer", QT_TRANSLATE_NOOP("PdfImport", "PDF Layer")},
};

const ComboEntry kFontRenderingEntries[] = {
    {"render-missing", QT_TRANSLATE_NOOP("PdfImport", "Draw missing fonts")},
    {"substitute", QT_TRANSLATE_NOOP("PdfImport", "Substitute missing fonts")},
    {"keep-missing", QT_TRANSLATE_NOOP("PdfImport", "Keep missing fonts' names")},
    {"delete-missing", QT_TRANSLATE_NOOP("PdfImport", "Delete missing font text")},
    {"render-all", QT_TRANSLATE_NOOP("PdfImport", "Draw all text")},
    {"delete-all", QT_TRANSLATE_NOOP("PdfImport", "Delete all text")},
};

/// Populate a QComboBox from a list of entries, storing the ID string in Qt::UserRole.
void populate_combo(QComboBox* combo, const ComboEntry* entries, int count) {
    combo->clear();
    for (int i = 0; i < count; ++i) {
        combo->addItem(QObject::tr(entries[i].label), QString::fromUtf8(entries[i].id));
    }
}

/// Find the combo index whose UserRole data matches the given ID string.
int combo_index_by_id(QComboBox* combo, const std::string& id) {
    for (int i = 0; i < combo->count(); ++i) {
        if (combo->itemData(i, Qt::UserRole).toString().toStdString() == id) {
            return i;
        }
    }
    return 0;
}

/// Get the ID string for the currently selected combo item.
std::string combo_current_id(QComboBox* combo) {
    int idx = combo->currentIndex();
    if (idx < 0) return {};
    return combo->itemData(idx, Qt::UserRole).toString().toStdString();
}

} // namespace

// ---- Font list model column indices ----
enum FontCol {
    COL_ICON = 0,
    COL_FAMILY,
    COL_STYLE,
    COL_WEIGHT,
    COL_STRETCH,
    COL_STRATEGY_LABEL,
    COL_FONT_ID,     // hidden: int font ID
    COL_STRATEGY_ID, // hidden: int FontFallback value
    COL_COUNT
};

PdfImportDialog::PdfImportDialog(std::shared_ptr<PDFDoc> doc, const char* uri, Inkscape::Extension::Input* mod,
                                 QWidget* parent)
    : QWidget(parent)
    , _ui(std::make_unique<Ui::PdfImportDialog>())
    , _mod(mod)
    , _pdfDoc(std::move(doc))
    , _uri(uri ? uri : "") {
    _ui->setupUi(this);

    // Font list model
    _fontModel = new QStandardItemModel(0, static_cast<int>(FontCol::COL_COUNT), this);
    _fontModel->setHeaderData(FontCol::COL_ICON, Qt::Horizontal, tr("Family Name"));
    _fontModel->setHeaderData(FontCol::COL_STYLE, Qt::Horizontal, tr("Style"));
    _fontModel->setHeaderData(FontCol::COL_WEIGHT, Qt::Horizontal, tr("Weight"));
    _fontModel->setHeaderData(FontCol::COL_STRETCH, Qt::Horizontal, tr("Stretch"));
    _fontModel->setHeaderData(FontCol::COL_STRATEGY_LABEL, Qt::Horizontal, tr("Strategy"));
    _ui->fontList->setModel(_fontModel);
    // Hide the ID columns
    _ui->fontList->setColumnHidden(FontCol::COL_FONT_ID, true);
    _ui->fontList->setColumnHidden(FontCol::COL_STRATEGY_ID, true);
    _ui->fontList->header()->setStretchLastSection(true);

    setupCombos();
    setupConnections();
    setFonts(getPdfFonts(_pdfDoc));

    // Mesh slider initial value from prefs
    double precision = _mod ? _mod->get_param_float("approximationPrecision", 2.0) : 2.0;
    _ui->meshSlider->setValue(static_cast<int>(precision));

    // Set combo boxes from prefs
    if (_mod) {
        _ui->clipTo->setCurrentIndex(combo_index_by_id(_ui->clipTo, _mod->get_param_optiongroup("clipTo")));
        _ui->groupBy->setCurrentIndex(combo_index_by_id(_ui->groupBy, _mod->get_param_optiongroup("groupBy")));
        auto render_pref = _mod->get_param_optiongroup("fontRendering");
        _ui->fontRendering->setCurrentIndex(combo_index_by_id(_ui->fontRendering, render_pref));
        // Apply the default font strategies
        setFontStrategies(SvgBuilder::autoFontStrategies(pref_to_font_strategy(render_pref), getPdfFonts(_pdfDoc)));

        _ui->embedImages->setChecked(_mod->get_param_bool("embedImages", true));
        _ui->convertColors->setChecked(_mod->get_param_bool("convertColors", true));
        _ui->importPages->setChecked(_mod->get_param_bool("importPages", true));
    }

    // Preview setup
    _renderThumb = false;
    _thumbData = nullptr;

#ifdef HAVE_POPPLER_CAIRO
    _renderThumb = true;
    _totalPages = _pdfDoc->getCatalog()->getNumPages();

    // Create PopplerDocument from the file URI
    std::string filename = _pdfDoc->getFileName()->getCString();
    QFileInfo fi(QString::fromStdString(filename));
    if (!fi.isAbsolute()) {
        filename = QDir::currentPath().toStdString() + "/" + filename;
    }
    QString full_uri = QUrl::fromLocalFile(QString::fromStdString(filename)).toString();
    if (!full_uri.isEmpty()) {
        _popplerDoc = poppler_document_new_from_file(full_uri.toUtf8().constData(), nullptr, nullptr);
    }
#else
    _totalPages = _pdfDoc->getCatalog()->getNumPages();
#endif

    _ui->pageNumbers->setEnabled(_totalPages > 1);
    _ui->previewArea->setPreviewSize(_previewWidth, _previewHeight);

    // Initial preview
    setPreviewPage(1);
}

PdfImportDialog::~PdfImportDialog() {
#ifdef HAVE_POPPLER_CAIRO
    if (_popplerDoc) {
        g_object_unref(G_OBJECT(_popplerDoc));
    }
#endif
    if (_thumbData) {
        gfree(_thumbData);
    }
}

// ---- public API ----

bool PdfImportDialog::showDialog() {
    QDialog dlg(nullptr);
    dlg.setWindowTitle(tr("PDF Import Settings"));
    dlg.setModal(true);
    dlg.setSizeGripEnabled(true);
    dlg.setMinimumSize(400, 400);

    auto layout = new QVBoxLayout(&dlg);
    layout->setContentsMargins(0, 0, 0, 0);

    // Reparent ourselves into the dialog
    QWidget::setParent(&dlg);
    layout->addWidget(this);

    // Connect the button box to the dialog
    QObject::connect(_ui->buttonBox, &QDialogButtonBox::accepted, &dlg, &QDialog::accept);
    QObject::connect(_ui->buttonBox, &QDialogButtonBox::rejected, &dlg, &QDialog::reject);

    auto result = dlg.exec();

    // Reparent back so we don't get deleted when dlg is destroyed
    QWidget::setParent(nullptr);

    return result == QDialog::Accepted;
}

bool PdfImportDialog::getImportPages() const {
    return _ui->importPages->isChecked();
}

std::string PdfImportDialog::getSelectedPages() const {
    if (_ui->pageNumbers->isEnabled()) {
        return _currentPages;
    }
    return "all";
}

PdfImportType PdfImportDialog::getImportMethod() const {
    return static_cast<PdfImportType>(_ui->importType->currentIndex());
}

FontStrategies PdfImportDialog::getFontStrategies() const {
    FontStrategies fs;
    if (!_fontModel) return fs;

    for (int row = 0; row < _fontModel->rowCount(); ++row) {
        int fontId = _fontModel->item(row, FontCol::COL_FONT_ID)->data(Qt::DisplayRole).toInt();
        int stratId = _fontModel->item(row, FontCol::COL_STRATEGY_ID)->data(Qt::DisplayRole).toInt();
        fs[fontId] = static_cast<FontFallback>(stratId);
    }
    return fs;
}

void PdfImportDialog::setFontStrategies(const FontStrategies& fs) {
    if (!_fontModel) return;

    for (int row = 0; row < _fontModel->rowCount(); ++row) {
        int fontId = _fontModel->item(row, FontCol::COL_FONT_ID)->data(Qt::DisplayRole).toInt();
        auto it = fs.find(fontId);
        if (it == fs.end()) continue;

        auto value = it->second;
        auto stratIdItem = _fontModel->item(row, FontCol::COL_STRATEGY_ID);
        if (!stratIdItem) continue;

        stratIdItem->setData(static_cast<int>(value), Qt::DisplayRole);

        // Update the combo box widget to reflect the strategy
        auto combo =
            qobject_cast<QComboBox*>(_ui->fontList->indexWidget(_fontModel->index(row, FontCol::COL_STRATEGY_LABEL)));
        if (combo) {
            QSignalBlocker blocker(combo);
            for (int i = 0; i < combo->count(); ++i) {
                if (combo->itemData(i).toInt() == static_cast<int>(value)) {
                    combo->setCurrentIndex(i);
                    break;
                }
            }
        }
    }
}

// ---- setup ----

void PdfImportDialog::setupCombos() {
    populate_combo(_ui->clipTo, kClipToEntries, std::size(kClipToEntries));
    populate_combo(_ui->groupBy, kGroupByEntries, std::size(kGroupByEntries));
    populate_combo(_ui->fontRendering, kFontRenderingEntries, std::size(kFontRenderingEntries));
}

void PdfImportDialog::setupConnections() {
    QObject::connect(_ui->pageNumbers, &QLineEdit::textChanged, this, &PdfImportDialog::onPageNumberChanged);
    QObject::connect(_ui->prevPage, &QPushButton::clicked, this, &PdfImportDialog::onPrevPage);
    QObject::connect(_ui->nextPage, &QPushButton::clicked, this, &PdfImportDialog::onNextPage);
    QObject::connect(_ui->meshSlider, &QSlider::valueChanged, this, &PdfImportDialog::onMeshSliderChanged);

    QObject::connect(_ui->clipTo, qOverload<int>(&QComboBox::currentIndexChanged), this,
                     &PdfImportDialog::onClipToChanged);
    QObject::connect(_ui->groupBy, qOverload<int>(&QComboBox::currentIndexChanged), this,
                     &PdfImportDialog::onGroupByChanged);
    QObject::connect(_ui->fontRendering, qOverload<int>(&QComboBox::currentIndexChanged), this,
                     &PdfImportDialog::onFontRenderingChanged);

    QObject::connect(_ui->embedImages, &QCheckBox::toggled, this, &PdfImportDialog::onEmbedImagesToggled);
    QObject::connect(_ui->convertColors, &QCheckBox::toggled, this, &PdfImportDialog::onConvertColorsToggled);
    QObject::connect(_ui->importPages, &QCheckBox::toggled, this, &PdfImportDialog::onImportPagesToggled);

    // Checkbox toggles visibility of the font list tree
    QObject::connect(_ui->fontListToggle, &QCheckBox::toggled, _ui->fontList, &QWidget::setVisible);
    _ui->fontList->setVisible(_ui->fontListToggle->isChecked());
}

// ---- slots ----

void PdfImportDialog::onPageNumberChanged() {
    _currentPages = _ui->pageNumbers->text().toStdString();
    auto nums = Inkscape::parseIntRange(_currentPages, 1, _totalPages);
    if (!nums.empty()) {
        setPreviewPage(*nums.begin());
    }
}

void PdfImportDialog::onPrevPage() {
    setPreviewPage(_previewPage - 1);
}

void PdfImportDialog::onNextPage() {
    setPreviewPage(_previewPage + 1);
}

void PdfImportDialog::onMeshSliderChanged(int value) {
    // Update the precision label
    int min = _ui->meshSlider->minimum();
    int max = _ui->meshSlider->maximum();
    int idx = static_cast<int>(std::floor((value - min) / static_cast<double>(max - min) * 4.0));
    idx = std::min(idx, 3);
    _ui->meshLabel->setText(tr(kPrecisionLabels[idx]));

    if (_mod) {
        _mod->set_param_float("approximationPrecision", static_cast<double>(value));
    }
}

void PdfImportDialog::onClipToChanged(int) {
    if (_mod) _mod->set_param_optiongroup("clipTo", combo_current_id(_ui->clipTo).c_str());
}

void PdfImportDialog::onGroupByChanged(int) {
    if (_mod) _mod->set_param_optiongroup("groupBy", combo_current_id(_ui->groupBy).c_str());
}

void PdfImportDialog::onFontRenderingChanged(int) {
    auto id = combo_current_id(_ui->fontRendering);
    if (_mod) _mod->set_param_optiongroup("fontRendering", id.c_str());
    // Reset per-font strategies with the new global default
    setFontStrategies(SvgBuilder::autoFontStrategies(pref_to_font_strategy(id), getPdfFonts(_pdfDoc)));
}

void PdfImportDialog::onEmbedImagesToggled(bool checked) {
    if (_mod) _mod->set_param_bool("embedImages", checked);
}

void PdfImportDialog::onConvertColorsToggled(bool checked) {
    if (_mod) _mod->set_param_bool("convertColors", checked);
}

void PdfImportDialog::onImportPagesToggled(bool checked) {
    if (_mod) _mod->set_param_bool("importPages", checked);
}

// ---- font list ----

void PdfImportDialog::setFonts(const FontList& fonts) {
    _fontModel->removeRows(0, _fontModel->rowCount());

    if (!fonts) return;

    for (auto& [font, data] : *fonts) {
        int row = _fontModel->rowCount();
        _fontModel->insertRow(row);

        // Icon column
        auto iconItem = new QStandardItem;
        if (font->isCIDFont()) {
            iconItem->setIcon(QIcon::fromTheme("text-convert-to-regular"));
        } else {
            iconItem->setIcon(QIcon::fromTheme(data.found ? "on" : "off-outline"));
        }
        _fontModel->setItem(row, FontCol::COL_ICON, iconItem);

        // Family
        auto familyItem = new QStandardItem;
        QString family = !data.family.empty() ? QString::fromStdString(data.family)
                                              : QString::fromStdString(data.name + " -> " + data.getSubstitute());
        familyItem->setText(family);
        _fontModel->setItem(row, FontCol::COL_FAMILY, familyItem);

        // Style, Weight, Stretch
        _fontModel->setItem(row, FontCol::COL_STYLE, new QStandardItem(QString::fromStdString(data.style)));
        _fontModel->setItem(row, FontCol::COL_WEIGHT, new QStandardItem(QString::fromStdString(data.weight)));
        _fontModel->setItem(row, FontCol::COL_STRETCH, new QStandardItem(QString::fromStdString(data.stretch)));

        // Strategy label item — empty text, the combo box is the visual
        auto stratLabelItem = new QStandardItem;
        stratLabelItem->setEditable(false);
        _fontModel->setItem(row, FontCol::COL_STRATEGY_LABEL, stratLabelItem);

        // Hidden: font ID
        auto fontIdItem = new QStandardItem;
        fontIdItem->setData(font->getID()->num, Qt::DisplayRole);
        _fontModel->setItem(row, FontCol::COL_FONT_ID, fontIdItem);

        // Hidden: strategy ID
        auto stratIdItem = new QStandardItem;
        stratIdItem->setData(0, Qt::DisplayRole);
        _fontModel->setItem(row, FontCol::COL_STRATEGY_ID, stratIdItem);

        // Install a per-row combo box for the strategy column
        auto combo = new QComboBox;
        combo->setSizePolicy(QSizePolicy::Expanding, QSizePolicy::Fixed);
        for (auto& e : kStrategyEntries) {
            combo->addItem(tr(e.label), e.id);
        }
        _ui->fontList->setIndexWidget(_fontModel->index(row, FontCol::COL_STRATEGY_LABEL), combo);

        // Connect combo change to update the hidden strategy ID
        QObject::connect(combo, qOverload<int>(&QComboBox::currentIndexChanged), this, [this, row](int comboIndex) {
            auto combo = qobject_cast<QComboBox*>(sender());
            if (!combo) return;
            int stratId = combo->itemData(comboIndex).toInt();
            auto stratIdItem = _fontModel->item(row, FontCol::COL_STRATEGY_ID);
            if (stratIdItem) stratIdItem->setData(stratId, Qt::DisplayRole);
        });
    }

    // Resize columns to contents
    _ui->fontList->resizeColumnToContents(FontCol::COL_ICON);
    _ui->fontList->resizeColumnToContents(FontCol::COL_STYLE);
    _ui->fontList->resizeColumnToContents(FontCol::COL_WEIGHT);
    _ui->fontList->resizeColumnToContents(FontCol::COL_STRETCH);
}

// ---- preview rendering ----

void PdfImportDialog::setPreviewPage(int page) {
    if (page < 1 || page > _totalPages) return;

    _previewPage = page;
    _ui->prevPage->setEnabled(page > 1);
    _ui->nextPage->setEnabled(page < _totalPages);
    _ui->currentPage->setText(QString("%1 / %2").arg(page).arg(_totalPages));

    renderPreview();
}

void PdfImportDialog::renderPreview() {
#ifndef HAVE_POPPLER_CAIRO
    // Use the PDF's embedded thumbnail
    if (_thumbData) {
        gfree(_thumbData);
        _thumbData = nullptr;
    }

    auto page = _pdfDoc->getCatalog()->getPage(_previewPage);
    if (!page) return;

    if (!page->loadThumb(&_thumbData, &_thumbWidth, &_thumbHeight, &_thumbRowstride)) {
        _ui->previewArea->setImage({});
        return;
    }

    // Convert raw RGB data to QImage
    QImage img(_thumbData, _thumbWidth, _thumbHeight, _thumbRowstride, QImage::Format_RGB888);
    _ui->previewArea->setPreviewSize(_thumbWidth, _thumbHeight + 20);
    _ui->previewArea->setImage(img.copy()); // deep copy so _thumbData can be freed later
    return;

#else
    // Render via poppler-glib + cairo, then convert to QImage (like PagesPanel does)
    if (!_popplerDoc) {
        _ui->previewArea->setImage({});
        return;
    }

    auto page = _pdfDoc->getCatalog()->getPage(_previewPage);
    if (!page) return;

    // Get page size, accounting for rotation
    double width, height;
    int rotate = page->getRotate();
    if (rotate == 90 || rotate == 270) {
        height = page->getCropWidth();
        width = page->getCropHeight();
    } else {
        width = page->getCropWidth();
        height = page->getCropHeight();
    }

    // Calculate scaling to fit the preview area
    double scale_x = static_cast<double>(_previewWidth) / width;
    double scale_y = static_cast<double>(_previewHeight) / height;
    double scale = std::min(scale_x, scale_y);

    int thumb_w = static_cast<int>(std::ceil(width * scale));
    int thumb_h = static_cast<int>(std::ceil(height * scale));

    // Check if we already have a cached surface for this page
    auto it = _cairoSurfaces.find(_previewPage);
    if (it != _cairoSurfaces.end() && it->second) {
        cairo_surface_t* surface = it->second.get();
        cairo_surface_flush(surface);
        QImage img = Inkscape::UI::cairo_surface_to_qimage(surface);
        if (!img.isNull()) {
            _ui->previewArea->setPreviewSize(thumb_w, thumb_h);
            _ui->previewArea->setImage(img);
        }
        return;
    }

    // Render asynchronously (like the original)
    if (_previewRenderingInProgress) return;
    _previewRenderingInProgress = true;

    auto cairo_surface = std::shared_ptr<cairo_surface_t>(
        cairo_image_surface_create(CAIRO_FORMAT_ARGB32, thumb_w, thumb_h), cairo_surface_destroy);

    auto poppler_page = Inkscape::Util::GObjectPtr(poppler_document_get_page(_popplerDoc, _previewPage - 1));

    auto [src, dst] = Inkscape::Async::Channel::create();

    Inkscape::Async::fire_and_forget([cairo_surface, scale, poppler_page = std::move(poppler_page),
                                      channel = std::move(src), dialog = this, page = _previewPage]() mutable {
        cairo_t* cr = cairo_create(cairo_surface.get());
        cairo_set_source_rgba(cr, 1.0, 1.0, 1.0, 1.0);
        cairo_paint(cr);
        cairo_scale(cr, scale, scale);
        poppler_page_render(poppler_page.get(), cr);
        cairo_destroy(cr);

        channel.run([dialog, page] {
            dialog->_previewRenderingInProgress = false;
            if (dialog->_previewPage == page) {
                dialog->renderPreview();
            }
        });
    });

    _channels.push_back(std::move(dst));
    _cairoSurfaces[_previewPage] = std::move(cairo_surface);

    _ui->previewArea->setPreviewSize(thumb_w, thumb_h);
#endif
}

} // namespace Linea::UI
